### ISSUE TITLE
Page not opening

### ISSUE THREAD

**Issue by ismayt12** [wongchito/RailMapGenerator#101]
Hi! I'm here because when I try to open the github page, it doesn't work, same for the gitlab page, so can someone please help me, I will appreciate that, thank you!

**Comment by wongchito** [comment]
Hi! Could you right click on the page, choose "Inspect", and capture any log shown in the Console tab. Thanks!

**Comment by wongchito** [comment]
We have found an issue during the initial render of the app. We're fixing it currently. Sorry for the inconvenience!

**Comment by wongchito** [comment]
Hi! We have released the fix to the issue just now. Could you please try again on either GitHub or GitLab page. Thanks.

**Comment by ismayt12** [comment]
It works now, thank you so much!
