### ISSUE TITLE
门板图无法显示文字线

### ISSUE THREAD

**Issue by CES9943** [wongchito/RailMapGenerator#108]
如题，门板图中的文字线换乘只有英语能正常显示，中文均显示为“换乘号线”
![4A1D4A67-3980-4EC4-8BF1-7368BE764B00](https://user-images.githubusercontent.com/85996604/127471902-3b9f0dea-0f4c-44be-856e-fec3189ba712.png)

**Comment by thekingofcity** [comment]
感谢反馈，会尽快修复

**Comment by thekingofcity** [comment]
之前的处理逻辑未考虑繁体中文的情况，即使不考虑支持繁中也会有诸如磁悬浮或其他文字线的问题

所以，重新设计了连接多个换乘线路的函数。一些例子：

> 1号线  => 换乘1号线
> 1号线 2号线 => 换乘1，2号线
> 1号线 2号线 嘉闵线 => 换乘1，2号线，嘉闵线
> 1号线 2号线 嘉闵线 磁悬浮 => 换乘1，2号线，嘉闵线，磁悬浮
> 1号线 嘉闵线 => 换乘1号线，嘉闵线

由于上海地铁暂无数字线路与文字线路同站换乘的情况，故以上的缩略为猜测（注意龙阳路和上海南站被定义为系统外换乘所以不会在门板图上与其他系统内线路一起显示

最后，线路中带`\`即换行符的情况不予支持，上海地铁站名支持也只是为了compensate一大会址

以上

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/128588039-3ccf9bfa-69bc-448b-b28a-515fc44160b8.png)
![image](https://user-images.githubusercontent.com/3353040/128588099-8f999803-ce4a-4753-967c-0a41a1491784.png)
