### ISSUE TITLE
支线上无法形成快车交路

### ISSUE THREAD

**Issue by czj114514** [wongchito/RailMapGenerator#109]
如题如图，请求网站管理员修复。感激不尽！
![image](https://user-images.githubusercontent.com/88187329/127631501-3d66399f-6734-4bdc-9f95-dbdba0b8d7d7.png)

**Comment by thekingofcity** [comment]
上海地铁目前无有支线的线路开行大站车的情况，即没有标准格式参考，这一效果在实际出现前不会额外实现
