### ISSUE TITLE
关于多换乘线路显示排序问题

### ISSUE THREAD

**Issue by czj114514** [wongchito/RailMapGenerator#111]
![image](https://user-images.githubusercontent.com/88187329/127768857-a7ee233b-141e-4618-b371-d2d09b9627c5.png)
如题如图，外侧到内侧换乘图标顺序依次为5,12,13；但文字显示顺序却依次为13,12,5。希望管理员修复这个问题，感激不尽！

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/128588259-8cb94009-8de0-4bed-9270-845f976a88c9.png)
![image](https://user-images.githubusercontent.com/3353040/128588268-38b7e1da-2c82-4c80-8b33-8964f7884532.png)

**Comment by thekingofcity** [comment]
由于没有更多的回音而关闭。
