### ISSUE TITLE
something question with the generator

### ISSUE THREAD

**Issue by Clebohto** [wongchito/RailMapGenerator#116]
I had a question when I made my rail map. I used shmetro style and I edited transfer stations. But I saw the lines in the upper left corner of the station name changed their position after the pages refreshed. I changed a browser and opened its json but it's still like that. Is my computer's wrong or program's wrong?
(My English is not very well, Maybe there are something wrong in it XD)

**Comment by thekingofcity** [comment]
Could you share some screenshots and the saved json?

**Comment by Clebohto** [comment]
okay. May I show you at night?

**Comment by Clebohto** [comment]
I will do some things at night. I will send you now.
[report.zip](https://github.com/wongchito/RailMapGenerator/files/6989980/report.zip)

**Comment by thekingofcity** [comment]
I could not reproduce the *before* version. The railmap always shows the *after* version after several import.

Could you reproduce it after importing from the save file?

**Comment by Clebohto** [comment]
Sorry, I had something to do and I was busy.
I tried and it couldn't recover. By the way. I found there is a update before I opened with my comment. Did the update **change** something?

**Comment by thekingofcity** [comment]
Yes, there is a commit 564b1ff that fixed #111 which may solve the issue. However, as this issue looks like a bug, I left it open.

**Comment by Clebohto** [comment]
OK, I see. Thanks XD

**Comment by thekingofcity** [comment]
Hi, sorry for bringing this up again. But for stations that are not opened yet like 天顶柱北, what would the real Shanghai Metro do in the rail map? Will they just cover the station name with a blank sticker or anything else? I'm looking for an implementation that makes 暂缓开通 more real.
