### ISSUE TITLE
关于上海地铁模板中车内线路图的一些建议

### ISSUE THREAD

**Issue by pishen635** [wongchito/RailMapGenerator#117]
近期，本人在制作时发现内置门板图换乘文字线路时的英文有一些错误
例如：
换乘首都机场线-Interchange Line Capital Airport Express
换乘亦庄线-Interchange Line Yizhuang
而这两者的正确表达方式应为
换乘首都机场线-Interchange Capital Airport Express
换乘亦庄线-Interchange Yizhuang Line

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/130079991-6375b974-c074-49f5-bd3e-9cfd811cb213.png)
