### ISSUE TITLE
可否增加北京地铁的线路图模板

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [wongchito/RailMapGenerator#118]
闲着没事摸了几条线(=w=)
不行的话就算了 pwp
[Beijing Subway.zip](https://github.com/wongchito/RailMapGenerator/files/6991866/Beijing.Subway.zip)

**Comment by thekingofcity** [comment]
感谢您的支持与贡献，我们已经进行了合法性检查，之后会添加到项目中

PS: 会使用您的github账号名作为贡献者名，这样可以吗

**Comment by AnDanJuneUnderline** [comment]
好的，感谢

**Comment by wongchito** [comment]
Released https://github.com/wongchito/RailMapGenerator/releases/tag/rmg-3.9.11

**Comment by thekingofcity** [comment]
除了检查合法性之外应该还有点需要考虑的 ):

话说2号线作为环线在当前的版本中不受支持，是不是应该在 #24 实现之前从官方的实现模板中移除？

首都机场线好像有特殊的线路画法？网上搜了下没有太确定的图，如果有明确支持T3到T2的单向的话，感觉也不是很适合使用通用的模板

**Comment by wongchito** [comment]
Thanks for raising these concerns!

**Comment by AnDanJuneUnderline** [comment]
> 说2号线作为环线在当前的版本中不受支持，是不是应该在#24实现之前从官方的实现模板中移除？



2号线的模板在制作时引入了个人制作环线线路图的方法， #24 是本人的遗漏。



> 首都机场线好像有特殊的线路画法？网上搜了下没有太确定的图，如果有支持T3到T2的单向的话，感觉也不太适合使用通用的模板



的确有特殊的画法。首都机场线在制作时被无意当做了环线——北京地铁官方的线路图画法是T3 → T2，而非有T2 → T3的列车。

我同意两者的暂时移除。同时我为自己的疏忽感到抱歉。:(

**Comment by thekingofcity** [comment]
那就暂时使用将这两者移除吧（通过新的pr (:
