### ISSUE TITLE
Remember the previous used style

### ISSUE THREAD

**Issue by thekingofcity** [wongchito/RailMapGenerator#120]
Currently, opening https://wongchito.github.io/RailMapGenerator/ will always be redirected to https://wongchito.github.io/RailMapGenerator/mtr. This works fine of course. However, it would greatly helps those who regularly use other styles if it remembers the previous selected style.

**Comment by thekingofcity** [comment]
This could be pretty simple by changing the code [here](https://github.com/wongchito/RailMapGenerator/blob/master/src/svgs/svg.tsx#L64). However, it seems that we do not have the `RmgStyle` in the param, which makes the upgrade a bit more complicated.

**Comment by wongchito** [comment]
It's possible to store RmgStyle in localStorage and read it when app loads, like RmgScale. 

https://github.com/wongchito/RailMapGenerator/blob/master/src/index.tsx#L82

https://github.com/wongchito/RailMapGenerator/blob/master/src/svgs/svg.tsx#L32

**Comment by thekingofcity** [comment]
Great to see the implemented similar feature :)

PS: This is duplicate of #63
