### ISSUE TITLE
Unable to change wide of "Station nameplate width" and "Width of circuit diagram".

### ISSUE THREAD

**Issue by xiaobaimao233** [wongchito/RailMapGenerator#131]
When I type the number value of it, it dosen't show, and when I want to delete the value, the old value can't delete and I can't type the new value, I hope the author will fix this problem, thanks.

**Comment by wongchito** [comment]
Hi all,

We're investigating the root cause of this issue. We've released a quick fix for it but it's not perfectly solved the issue. We'll back to you soon with the proper fix.

Sorry for the inconvenience and thank you for using RMG.

**Comment by wongchito** [comment]
Fixed in #206
