### ISSUE TITLE
Cannot appear in Canvas Size

### ISSUE THREAD

**Issue by LukesonPaul9487** [wongchito/RailMapGenerator#132]
I want to change the rail map width as 1000 px, but when I cancel one of value of 0, I can't continue cancel number, even though is change the width, the value of canvas size is still appear as 1000 px, can someone fix it?

**Comment by wongchito** [comment]
Hi LukesonPaul9487, 

We've acknowledged this issue. Please refer to #131 for further discussion. Thanks!
