### ISSUE TITLE
北京地铁“一八贯通”与新增7号线的更新

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [wongchito/RailMapGenerator#140]
开学了 工作效率好慢;w;
先把这俩传上来吧
[bjsubway-sep25th.zip](https://github.com/wongchito/RailMapGenerator/files/7229228/bjsubway-sep25th.zip)

**Comment by AnDanJuneUnderline** [comment]
ps：一八贯通指的是1号线和八通线的贯通，如果更新了请将八通线的模板删除٩( 'ω' )و

**Comment by AnDanJuneUnderline** [comment]
thx XD

**Comment by thekingofcity** [comment]
Hi, we would like to thank you for your contribution, so we put your name in the `info` panel and project `readme`. Looking for more!

![image](https://user-images.githubusercontent.com/3353040/139860647-01283189-938b-4a02-8ef6-813de8d25165.png)

**Comment by AnDanJuneUnderline** [comment]
thanks XD
