### ISSUE TITLE
能否将使用浦江线颜色的线路的已经过部分改为白色

### ISSUE THREAD

**Issue by BSOD-qian** [wongchito/RailMapGenerator#161]
在现实中，浦江线已经过部分使用白色以和未经过部分区分
![img](http://image.thepaper.cn/wap/image/7/89/194.jpg)

**Comment by thekingofcity** [comment]
您好，图片好像有些问题没有办法加载出来。不过这个功能依赖 #162 ，所以要等修复后才能更新，估计尚需一段时日，感谢您在这段时间的耐心等待。

**Comment by thekingofcity** [comment]
嗨，虽然 #162 不是必须的即此功能可以被当作上海风格的一个特例来实现，但由于 #181 实现的困难（需要计算在V5中修改的底层数据结构），我将考虑在V5发布后再来实现这一功能。感谢您之后的耐心等待，谢谢！

**Comment by thekingofcity** [comment]
- [ ] #162 
- [ ] #181

**Comment by thekingofcity** [comment]
嗨，感谢您的等待，我使用了一种变通方法，使得 #181 也不是这个问题被修复的必要条件。在 286fc76 中被修复，更新于`3.10.7`。

![rmg kaxg 人民广场 People's_Square](https://user-images.githubusercontent.com/3353040/142722607-360bd376-7eef-472b-82ff-1ddcd4ad790b.png)
![rmg qsju 上海汽车城 Shanghai_Automobile_City](https://user-images.githubusercontent.com/3353040/142722609-b5fd47c9-4671-4395-9c63-9716a231403b.png)
![rmg op34 鹤沙航城 _____Heshahangcheng](https://user-images.githubusercontent.com/3353040/142722608-12763c4d-dc0c-47bb-b100-af155690adad.png)

欢迎您进行体验并检查是否还有不完善的地方，并且也欢迎您提交浦江线的线路模板，可以参考[这里](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates)。

**Comment by thekingofcity** [comment]
参考资料：

- https://stackoverflow.com/questions/49693471/svg-border-outline-for-group-of-elements
- https://stackoverflow.com/questions/41639049/replace-one-color-using-svg-filters
- https://stackoverflow.com/questions/14663252/matching-a-color-in-svg-with-fecolormatrix
- https://stackoverflow.com/questions/21977929/match-colors-in-fecolormatrix-filter
- https://stackoverflow.com/questions/58719609/svg-nested-filter-make-white-transparent
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComponentTransfer
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feColorMatrix
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feComposite
- https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/operator

**Comment by thekingofcity** [comment]
这是一个已知的小问题。

![image](https://user-images.githubusercontent.com/3353040/142722894-493b9899-bc1a-42f1-a300-67c218881d5e.png)

**Comment by thekingofcity** [comment]
嗨，抱歉之前处理此问题时未考虑 `runin` 画板，现在已修复，抱歉这段时间给您带来的不便。

![image](https://user-images.githubusercontent.com/3353040/147875100-c2a139db-1819-4c2b-b5d5-ff5affe43903.png)
