### ISSUE TITLE
Moscow Metro Indoor map Style

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#163]
![image](https://user-images.githubusercontent.com/92020676/139876676-f5911b03-0a12-4041-87be-3488f9e8e85c.png)
I have found the Indoor map of Moscow Metro. I got it from _https://www.artlebedev.com/metro/line-map2/_ , where the current official map of Moscow Metro designer comes from. Old versions of Moscow Metro Indoor map can also be discovered there.
Like many metro systems in Europe, Moscow Metro is without screen doors. I think it's nice that I can edit a line map in the style of Moscow Metro. 
The font is "**Moscow Sans Regular**" but ttf files couldn't be updated here. Maybe it could be updated in other way.
By the way, I tried to detect the colors of Moscow Metro Lines. But Some Lines could change their colors. The Moscow Central Circle line (not real metro transit system, with current number 14) and the Moscow Monorail (with current number 13) belong in the future maybe not to Moscow Metro anymore and become their own symbols. The new lines under construction could take their line numbers. 
(See https://metromap.moscow/ru)

**Comment by thekingofcity** [comment]
Hi, having more styles is always our commitment.

But all of our core contributors are working on features like #24 and #41, so it's like a *we'd love to but we have no time* situation.

See [comments in #31](https://github.com/wongchito/RailMapGenerator/issues/31#issuecomment-609608213) and also #38.

PS: Add a new style only requires some basic knowledge about `Typescript`, `HTML`, and developing tools like `git` and `vscode`. We could provide any help if you would like to add it by yourself. 😁

**Comment by thekingofcity** [comment]
Hi, I referenced the new color palette in the new issue.
