### ISSUE TITLE
Texts are shown in wrong position in certain conditions

### ISSUE THREAD

**Issue by nanhuajiaren** [wongchito/RailMapGenerator#17]
Texts are not shown correctly while using Shanghai Metro style , but just in the preview on top of the edit view. When the names of the terminal stations are too long, It just covers the name of current station. The transfers at the terminal station go out of the screen. The problem totally disapears in the final export.
I'm using mobile device , where screen sizes are different. I have no idea whether the problem appears on desktop version.

**Comment by thekingofcity** [comment]
Maybe using a bigger height will solve this problem?
I'm not 100% sure what the situation is. A screenshot and the project json file may better illustrate this :)
