### ISSUE TITLE
Adding color palettes of Santiago, Cairo, and Klang Valley

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#176]
[santiago.txt](https://github.com/wongchito/RailMapGenerator/files/7528363/santiago.txt)
[cairo.txt](https://github.com/wongchito/RailMapGenerator/files/7528365/cairo.txt)
The line colors of Santiago and Cairo are detected. All information included in the txt files.

**Comment by thekingofcity** [comment]
Hi, the Cairo Meyto seems to be located in the Greater Cairo area in Wiki. Would you like to make a double-check on its name and coverage? If so, comment on a new name like `Cairo (Greater Cairo Area)` in English.

> The Cairo Metro is the rapid transit system in Greater Cairo, Egypt.
> https://en.wikipedia.org/wiki/Cairo_Metro

```typescript
    {
        id: CityCode.Tokyo,
        country: 'JP',
        name: {
            en: 'Tokyo (Greater Tokyo Area)',
            ja: '東京（首都圏）',
            'zh-Hans': '东京（首都圈）',
            'zh-Hant': '東京（首都圈）',
        },
    },
```

> This is what we have for Tokyo.

And also, Cairo.txt for steps 3 and 5 should be:

```
Arabic = 'ar',

{
    id: 'cr1',
    name: {
        en: 'Line 1',
        [LanguageCode.عربي]: 'خط 1',
        'zh-Hans': '1号线',
        'zh-Hant': '1號線',
    },
    colour: '#144996',
},
```

instead of

```
عربي = 'ar',

{
    id: 'cr1',
    name: {
        en: 'Line 1',
        [LanguageCode.عربي]: 'خط 1',
        'zh-Hans': '1号线',
        'zh-Hant': '1號線',
    },
    colour: '#144996',
},
```

There is also missing `{` in Santiago.

---

Anyway, these are minor issues, and we'd like to thank you for your contribution again! 😋

**Comment by linchen1965** [comment]
[cairo2.txt](https://github.com/wongchito/RailMapGenerator/files/7532315/cairo2.txt)
New version of Cairo Metro Line colors. Thanks for the  hints.

**Comment by thekingofcity** [comment]
Hi, the txt file did not upload correctly. `Not Found` displayed.

**Comment by linchen1965** [comment]
> Hi, the txt file did not upload correctly. `Not Found` displayed.
[cairo2.txt](https://github.com/wongchito/RailMapGenerator/files/7533723/cairo2.txt)
[KL.txt](https://github.com/wongchito/RailMapGenerator/files/7533794/KL.txt)
Uploaded again. Also uploaded a new txt of Greater KL/Klang Valley Line colors.

**Comment by thekingofcity** [comment]
Hi, they are added in a6cd4f6 and released in `3.10.4`.

*A star at the top right corner would make us certain about what we do and devote more to this 😁*

**Comment by linchen1965** [comment]
Hi, thanks for that but I'am sorry that I found a small error in the color code of Santiago metro:
{
    id: 'stg5',
    name: {
        en: 'Line 5',
        es: 'Línea 5',
        'zh-Hans': '5号线',
        'zh-Hant': '5號線',
    },
    colour: '#**0B9444**',
},
[santiago2.txt](https://github.com/wongchito/RailMapGenerator/files/7539326/santiago2.txt)
And here is the corrected version

**Comment by thekingofcity** [comment]
Hi, it is updated in the source code, but will be released in the next version, which it's date is unknown yet since the issue seems quite unurgent.

*A star at the top right corner would make us certain about what we do and devote more to this 😁*
