### ISSUE TITLE
深圳地铁模版

### ISSUE THREAD

**Issue by xiany114514** [wongchito/RailMapGenerator#177]
制作了1-4号线（不含2号线）。
[深圳4.zip](https://github.com/wongchito/RailMapGenerator/files/7533041/4.zip)
[深圳1.zip](https://github.com/wongchito/RailMapGenerator/files/7533042/1.zip)
[深圳3.zip](https://github.com/wongchito/RailMapGenerator/files/7533043/3.zip)

**Comment by thekingofcity** [comment]
Hi, thanks for your very first contribution. These lines look great but the city info is missed (mentioned in step 7 of this [Wiki](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates)).

After this, we should be able to merge your contribution and put your name on the info panel as soon as possible.

**Comment by xiany114514** [comment]
Thanks.Yanfang Line(Beijing)：
[content.json.zip](https://github.com/wongchito/RailMapGenerator/files/7533250/content.json.zip)

**Comment by xiany114514** [comment]
我不会加啊…

**Comment by thekingofcity** [comment]
嗨，别担心，我们已经帮你处理完了其他剩余的步骤，在 f04583b 中添加了这三条线路。再次感谢您的贡献，我们会在下一次更新`3.10.4`中展现这三条新线路。

同时我们也注意到了一些wiki中不足的地方，再下一次的更新前别忘了再查看一次wiki哦😁

**Comment by xiany114514** [comment]
> 3.10.4

3.10.4什么时候更新呢

**Comment by xiany114514** [comment]
> 再次感谢您的贡献，我们会在下一次更新3.10.4中展现这三条新线路。
**之后还会制作更多线路，问下你们更新的频率大概是多少时间**

**Comment by xiany114514** [comment]
@thekingofcity

**Comment by thekingofcity** [comment]
Hi, they are added in f04583b and released in `3.10.4`.

*A star at the top right corner would make us certain about what we do and devote more to this 😁*
