### ISSUE TITLE
港鐵樣式支線顯示錯位

### ISSUE THREAD

**Issue by OriginCode** [wongchito/RailMapGenerator#18]
![image](https://user-images.githubusercontent.com/17294071/75137364-5aaccc80-5722-11ea-875c-2f059b16de92.png)

**Comment by wongchito** [comment]
Thanks for getting in touch. 

This is not a bug but a feature. MTR officially uses this 'peanut'-shaped station icons to draw Sheung Shui and Tseung Kwan O stations on MTR system map, in-train map (East Rail Line) and information panels (mostly in stations of Tseung Kwan O Line). Lok Ma Chau branch and LOHAS Park branch are therefore drawn with slightly shift to incorporate with the `peanut`-shaped icons.

**Comment by OriginCode** [comment]
Thanks
