### ISSUE TITLE
自制吉隆坡快捷通轨道模板/Rapid KL template

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#180]
[rapidKL.zip](https://github.com/wongchito/RailMapGenerator/files/7547283/rapidKL.zip)
自己做了几条吉隆坡轨道交通线路图模板，包括由快捷通轨道运营的五条线（安邦线、大城堡线、格拉那再也线、吉隆坡单轨、加影线）。
Self made rapid KL Line templates. Include 5 current lines in operation.(LRT Ampang Line, LRT Sri Pataling Line, LRT Kelana Jaya Line, KL Monorail, MRT Kajang Line)

**Comment by thekingofcity** [comment]
Hi, for line templates, you may want to check the [Wiki on how to contribute to line templates section](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates).

**Comment by linchen1965** [comment]
> Hi, for line templates, you may want to check the [Wiki on how to contribute to line templates section](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates).

Sorry, I didn't understand the hint :(

**Comment by thekingofcity** [comment]
Never mind, it’s just a preprocessing step which will speed up the merge. I’ll add it in the coming days.

**Comment by thekingofcity** [comment]
Hi, they are added in 57298e4 and released in 3.10.23

> Wiki is about the line names in English, Malay, and Chinese. It took me some time to find these translations.
