### ISSUE TITLE
Wrong Translation of Shanghai Metro Line 9 Template

### ISSUE THREAD

**Issue by XHG78999** [wongchito/RailMapGenerator#184]
Correct / Wrong
Jinhai Road Jinhai Lu
Caohejing Hi-Tech Park Caohejing High-Tech Park
Sijing Sijin
Sheshan SheShan

**Comment by XHG78999** [comment]
Offical Indoor Map https://bkimg.cdn.bcebos.com/pic/32fa828ba61ea8d3fd1ff3927044274e251f95caf25c

**Comment by XHG78999** [comment]
![image](https://user-images.githubusercontent.com/53939187/142759212-84a5fa48-013b-46d7-8c4c-181650b361d6.png)

**Comment by thekingofcity** [comment]
Hi, the link is unreachable, maybe a `referer` is needed?

Besides, *Caohejing Hi-Tech Park* and *Sheshan* are what I see in the Baike.

**Comment by XHG78999** [comment]
> Hi, the link is unreachable, maybe a `referer` is needed?
> 
> Besides, _Caohejing Hi-Tech Park_ and _Sheshan_ are what I see in the Baike.

Emm, The picture need s a referer fron https://baike.baidu.com/ .But It is on the last comment of me too.
In the really shanghai metro, the screen always shows "Caohejing Hi-Tech Park", and "Shenshan" is an lower case/upper case error.The "Sijing" is a pinyin error too.

**Comment by thekingofcity** [comment]
Wow, so you are also a baike contributor 🎉 Great job!

I updated the aforementioned translation issues in e12e1863 and should be updated in the next release.

PS: I am always curious about where did the baike get the images like the `indoor` map. Would you like to share some ideas on it?
