### ISSUE TITLE
Bugs by exporting png (Guangzhou metro style)

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#185]
![rmg lyqw 莲花_ Lianhua](https://user-images.githubusercontent.com/92020676/142820160-e05aa562-91a7-4eae-a739-f1d6984b37a8.png)
Bug 1: "Next station" moved out of the picture
![rmg qbbb 南桥农场_ Nanqiao_Farm](https://user-images.githubusercontent.com/92020676/142820484-ac1c1d92-3046-4232-94c4-71e27ec34dc3.png)
Bug 2: Station number covers the station name

**Comment by wongchito** [comment]
Hi @linchen1965, 

Does this issue occur when you're downloading 1 station or all stations?

**Comment by wongchito** [comment]
To correctly display Guangzhou style Running-in board, the element has to be rendered on screen, then some statistics is captured to move the components to the correct place. This is a similar issue as #182. Hence close this issue and track further in #182.
