### ISSUE TITLE
建议北京新增11、17、19号线颜色模板

### ISSUE THREAD

**Issue by GrassRabbit1410** [wongchito/RailMapGenerator#186]
北京地铁11、17、19号线年底即将开通，经PS测得以下颜色数据：
北京11：背景色 #89D7FD，RGB（137，215，253），前景色白
![908fa0ec08fa513d2697e586613d42fbb2fb43167310-bkimg-process_v_1_rw_3_rh_2_maxl_1050_pad_1_color_ffffff](https://user-images.githubusercontent.com/94828677/142833105-0c734b23-bcfb-4355-b542-70380cf1dd08.png)

北京17：背景色 #1FA1A1，RGB（31，161，161），前景色白
![bf096b63f6246b600c335dabbea80d4c510fd8f904e9](https://user-images.githubusercontent.com/94828677/142833144-625a1515-44e5-4c19-a8ed-a3d6bae89bfa.jpeg)

北京19：背景色 #CF9DC2，RGB（207，157，194），前景色 #001E2F，RGB（0，30，47）
![f703738da9773912b31be1d966499118367adab44470-bkimg-process_v_1_rw_3_rh_2_maxl_1050_pad_1_color_ffffff](https://user-images.githubusercontent.com/94828677/142833183-3e02845a-f8aa-4396-bd01-aeedcd4148a1.jpeg)

**Comment by GrassRabbit1410** [comment]
Beijing Metro Line 11, Line 17 and Line 19 will be opened recently. The following color value are measured by Photoshop:
Line 11:
Background Color: #89D7FD, RGB (137, 215, 253)
Foreground Color: white
Line 17:
Background Color: #1FA1A1, RGB (31, 161, 161)
Foreground Color: white
Line 19:
Background Color: #CF9DC2, RGB (207, 157, 194)
Foreground Color: #001E2F, RGB (0, 30, 47)

**Comment by thekingofcity** [comment]
嗨，谢谢您提出的建议。在收录这些信息前，请问您有标注了这些RGB数值的官方来源吗？如果没有的话，有来自官方的图片及其地址吗？

**Comment by GrassRabbit1410** [comment]
11号线线路颜色可能有变，暂时取消加入

**Comment by thekingofcity** [comment]
> 嗨，谢谢您提出的建议。在收录这些信息前，请问您有标注了这些RGB数值的官方来源吗？如果没有的话，有来自官方的图片及其地址吗？

方便提供一下来源吗？谢谢

**Comment by GrassRabbit1410** [comment]
暂无法找到证据

**Comment by thekingofcity** [comment]
好的，您可以等到正式开通后在官方的线路图上提取并确认颜色。有任何更新欢迎重新open此issue

**Comment by linchen1965** [comment]
![9IXGXBZMGQYSC92G@ I)J{O](https://user-images.githubusercontent.com/92020676/148690452-d0946e8f-34bb-4bc3-b9e7-0e0c5d9fae6a.png)
图源北京地铁官网，三条线路颜色前景色均为白色
11号线：ED796B
17号线：00A9A9
19号线：D6ABC1

**Comment by thekingofcity** [comment]
嗨，这三条线路颜色在 94f40bc 中被添加，更新于3.10.34，感谢您的支持与贡献！
