### ISSUE TITLE
广州地铁线路号错误（Bug）

### ISSUE THREAD

**Issue by BAS714** [wongchito/RailMapGenerator#188]

**Comment by BAS714** [comment]
![Uploading 247EEBB7-0B47-4BAC-A066-5EAFCB7221F0.png…]()

**Comment by thekingofcity** [comment]
嗨，图片没有成功上传，请等待图片链接出现后再点comment按钮

**Comment by BAS714** [comment]
[铁路线路图生成器.pdf](https://github.com/wongchito/RailMapGenerator/files/7604856/default.pdf)

**Comment by BAS714** [comment]
![Uploading 6E410644-4A6F-49DB-BEE7-2A7F9E7B750D.png…]()
