### ISSUE TITLE
增加哈尔滨地铁颜色模板色库/Add Harbin Metro to the line color bank 

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [wongchito/RailMapGenerator#193]
哈尔滨地铁规划的三条线路（1号线，2号线，3号线）已于11月26日开通（其中1号线东延、3号线西北半环暂未开通）。以下是哈尔滨地铁三条线路的RGB及HEX色值。
1号线/Line 1:R200 G16 B46 #C8102E
2号线/Line 2:R68 G175 B82 #44AF52
3号线/Line 3:R255 G199 B44 #FFC72C
Wiki对应内容：
Country Code:CN
Language Code:ZH
Foreground Color: R255 G255 B255 #FFFFFF
哈尔滨地铁官方网站：http://www.harbin-metro.com/index.html
数据来源：http://bxt.harbin.gov.cn/hrb_bxt/disshow.php?id=772792
PS：原回复中1号线为168C，而Pantone官网显示为棕色（R115 G56 B29 #73381D），推测大概应为186C，即上文提到的色值。

**Comment by thekingofcity** [comment]
嗨，感谢您的建议与颜色数据，我们会将其合入项目中。当然，如果你愿意按照[wiki](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#color-palette)的格式准备的话会进一步加速这个流程 🎉

**Comment by AnDanJuneUnderline** [comment]
[Harbin.txt](https://github.com/wongchito/RailMapGenerator/files/7645206/Harbin.txt)

**Comment by thekingofcity** [comment]
嗨，在 23f5876 中被添加，更新于 3.10.18

**Comment by AnDanJuneUnderline** [comment]
I'm sorry, but I checked and found it couldn't display on my phone. Although they were add to the code, but the web couldn't find a city called "Harbin".
![Screenshot_2021-12-03-19-55-17-921_com fexdo fileeditorx](https://user-images.githubusercontent.com/89013535/144598857-af78e5f3-7991-49ca-9b5e-721e87e4db93.jpg)
![Screenshot_2021-12-03-19-54-36-152_com microsoft emmx](https://user-images.githubusercontent.com/89013535/144598869-bbb8550f-e13c-411f-a32d-de7a16258af0.jpg)
![Screenshot_2021-12-03-19-58-40-781_com microsoft emmx](https://user-images.githubusercontent.com/89013535/144598936-231a02a3-c51d-4118-ba63-2595de5cf74e.jpg)

**Comment by thekingofcity** [comment]
Hi, sorry for forgetting the final stage of release. 3.10.18 should be online now.
