### ISSUE TITLE
增加无锡地铁颜色模板色库/Add Wuxi Metro to the line color bank

### ISSUE THREAD

**Issue by GrassRabbit1410** [wongchito/RailMapGenerator#194]
数据源：地方标准DB 3202/T 1025-2021 附录A
无锡地铁官网：http://www.wxmetro.net/
标准颜色：
1号线/Line 1：潘通1788C，RGB（238，39，55），#EE2737
2号线/Line 2：潘通354C，RGB（0，177，64），#00B140
3号线/Line 3：潘通2995C，RGB（0，169，224），#00A9E0
4号线/Line 4：潘通513C，RGB（147，50，142），#93328E
5号线/Line 5：潘通1235C，RGB（255，184，28），#FFB81C

**Comment by GrassRabbit1410** [comment]
Data source: Appendix A of local standard DB 3202 / T 1025-2021
Wuxi Metro official website:
http://www.wxmetro.net/
Standard color:
Line 1: Pantone 1788C, RGB (238, 39, 55), #EE2737
Line 2: Pantone 354C, RGB (0177, 64), #00B140
Line 3: Pantone 2995C, RGB (0169224), #00A9E0
Line 4: Pantone 513C, RGB (147, 50142), #93328E
Line 5: Pantone 1235C, RGB (255184, 28), #FFB81C

**Comment by GrassRabbit1410** [comment]
![Uploading Screenshot_20211202_112651_edit_1389615578314135.jpg…]()

**Comment by GrassRabbit1410** [comment]
文件截图
![Uploading Screenshot_20211202_112651_edit_1389615578314135.jpg…]()

**Comment by thekingofcity** [comment]
嗨，图片没有被正确上传，添加图片后请稍等片刻等Uploading Screenshot消失再点击Comment按钮。

同时，根据我们的[wiki](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#color-palette)准备好颜色模板数据会帮助我们更快的将此合入项目中，谢谢！

**Comment by GrassRabbit1410** [comment]
![Screenshot_20211202_112651_edit_1389615578314135](https://user-images.githubusercontent.com/94828677/144387634-ed925b2e-63d2-4b5b-9e64-c46690067266.jpg)

**Comment by GrassRabbit1410** [comment]
颜色模板数据
[Wuxi.txt](https://github.com/wongchito/RailMapGenerator/files/7641071/Wuxi.txt)

**Comment by GrassRabbit1410** [comment]
[Wuxi.txt](https://github.com/wongchito/RailMapGenerator/files/7641131/Wuxi.txt)

**Comment by thekingofcity** [comment]
嗨，在 ba60f8e 中被添加，更新于 3.10.15
