### ISSUE TITLE
Adding color palettes of Suzhou and Dalian

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#197]
[suzhou.txt](https://github.com/wongchito/RailMapGenerator/files/7655325/suzhou.txt)
[dalian.txt](https://github.com/wongchito/RailMapGenerator/files/7655328/dalian.txt)
The line colors of Suzhou and Dalian are detected. All information included in the txt files.
PS: About Dalian Metro Line colors- Line colors of Line 1, Line 2, Line 3, Line 5, Line 12 and Line 13 are from official page. Colors of Line 4, Line 6 and Line 8 are from a planning map of Line 4 by Dalian Metro Official. Colors of Line 7 and Line 9 are showed from a Dalian Metro planning map, where also show the right line colors of Line 1~5 and Line 12, Line 13. Other Line colors are detected from a color  palette version a few years ago.

**Comment by thekingofcity** [comment]
Hi, they are updated in c2272eb and released in 3.10.21
