### ISSUE TITLE
Changed the sorting of site numbers(bj4,bj5,bj9 and t1l)

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [wongchito/RailMapGenerator#199]
[bjsubway-dec6th.zip](https://github.com/wongchito/RailMapGenerator/files/7657068/bjsubway-dec6th.zip)
This is a small update, so there is no need to change the code.

**Comment by thekingofcity** [comment]
Hi, would you like to elaborate on the visual difference and the reason why you make these changes?

**Comment by AnDanJuneUnderline** [comment]
OK, Maybe I'm wrong. Beijing Technology Quality Control Office didn't change _Classification and code for facilities and equipments of urban rail transit_ after 2010. Now we can only refer to the DB11/T 717 - 2010. In the Page 146 of that, I found the station codes of M4 and M5 are increasing from north to south. So now I find it extremely difficult to lend the template established. I'm sorry for you.🙁

**Comment by thekingofcity** [comment]
So there are station code changes but you find it difficult to change the template?

**Comment by AnDanJuneUnderline** [comment]
Maybe I didn't say it clearly enough. Yesterday, I found the sorting rules from north to south in the published file. I thought it's unnecessary to change the sorting. I have some problems with my expression.
But now, I find unwritten rules in this.
![Screenshot_2021-12-08-06-46-58-505_com microsoft emmx](https://user-images.githubusercontent.com/89013535/145117689-3aed5bf7-8fc0-4785-a3cd-20d9d7b21130.jpg)
http://www.ditiezu.com/thread-550856-1-1.html

**Comment by thekingofcity** [comment]
So the station numbers will change in different directions? That's interesting but the current implementation doesn't have the ability to do that.

If this is an iconic character of Beijing Subway, open a new issue with the official naming convention.

Thanks for bringing this interesting fact.

**Comment by AnDanJuneUnderline** [comment]
Well, I asked for my friend who works in subway operating company, he said the station numbers were changeless, and the rules were from south to north and from west to east. It's not about down direction.

**Comment by thekingofcity** [comment]
Great, nothing needs to be changed.

**Comment by AnDanJuneUnderline** [comment]
Err... So the files I sent were modified according to such rules... The templates on the website don't follow this rule. It was a mistake. I knew this rule from the beginning, but I couldn't find a suitable evidence.

**Comment by thekingofcity** [comment]
Let's make it clear.

1. Station numbers in the current templates need to be changed.
2. There are no official documents requiring this.
3. But that's how numbers are labeled in the real world.

Are all of them correct?

**Comment by AnDanJuneUnderline** [comment]
Yeah, just like that.

**Comment by thekingofcity** [comment]
Hi, if only the station nums need to be changed. Then this online editor will be a good fit for it.

Visit https://github.dev/wongchito/RailMapGenerator and modify the `params.stn_list.[station id].num` in these files.

After you are satisfied with your change, click the `source control` icon of the left sidebar and text `#199 Changed the sorting of site numbers(bj4,bj5,bj9 and t1l)` and commit. Name the branch with any name you like and you are now able to create a pull request on the https://github.com/wongchito/RailMapGenerator/pulls page.

![image](https://user-images.githubusercontent.com/3353040/145220410-815f7172-5827-417b-ad17-836b4c7c64de.png)

**Comment by AnDanJuneUnderline** [comment]
OK, I'm finally free. I opened the web and it shown "Setting up your editer" for a long time. Could you please tell me why?
![捕获](https://user-images.githubusercontent.com/89013535/145757710-5dfa7402-8b33-4acd-a99d-b1407c9c73a1.PNG)

**Comment by thekingofcity** [comment]
No worries, I update them for you. Thanks for your patience and contribution. 😁

Updated in a8d129d and released in 3.10.35
