### ISSUE TITLE
Much canvas in one page ( Tab choose )

### ISSUE THREAD

**Issue by XHG78999** [wongchito/RailMapGenerator#202]
I am making an railmap for my MINECRAFT metro station building.Because of this station is a transfer station, I need to make the map of two lines. Now I need to Upload JSON,Download JSON,again and again.
It's very boring. I want have more than 1 canvas in one page to switch them easily.

**Comment by wongchito** [comment]
Hi XHG78999, 

In #40 we have planned to build a welcome page for RMG allowing user to switch between templates/files. 

This feature will be implemented in V5. 

Thanks for using RMG!
