### ISSUE TITLE
Refactor this project to pure front end project

### ISSUE THREAD

**Issue by XHG78999** [wongchito/RailMapGenerator#204]
As a programmer very hate non pure front end (Like Vue,React,etc.), Reading and Understanding this code is very hard.The non pure front end projects is very like an desktop application and it's harder to the programmers.If we refactor it to pure front end project, it will have fast speed, and easy code.
So I write this plan to refactor it:
## UI
Using MDUI to refactor.
## Image Generator
Need to rewrite all codes to front-end. I think we can cut them to more files.
## Templates
Cut to many files that we can edit them very easily.

About others..... I need to think it later.

**Comment by XHG78999** [comment]
This is an simulate image made by MDUI Online Editor ( For #40 and #202  ).
![image](https://user-images.githubusercontent.com/53939187/145675257-f4805034-4a58-491a-8f02-ec2589dbad21.png)
Index Image (#40)
![image](https://user-images.githubusercontent.com/53939187/145675276-88ba642d-a9cc-4be1-b30b-c5d113f5467d.png)
Part of a canvas page

The head nav of this demo is about #202 .

**Comment by wongchito** [comment]
Hi XHG78999,

# UI

I do like MDUI as a CSS asset, as it's more lightweight when building a small app. However, for a medium-sized project like RMG, using CSS asset and vanilla JavaScript will eventually become building another "framework". For both of me and the other main contributor @thekingofcity, we don't have much free time to build a framework from scratch -- so we decided to use React + MUI. 

# Image generator

Not sure if you're talking about the SVG components. If yes, I would like to hear more on it. 

# Template 

Not sure if I understand what you mean. 

NB: You may use Chinese if you find it difficult to describe this in English.

**Comment by wongchito** [comment]
Btw, we're building an new UI for V5. You may check a demo version in:

https://wongchito.github.io/uat-rail-map-generator/v5

**Comment by XHG78999** [comment]
(Ok,I use Chinese now.)
额。。。我比你们还忙，但是我打死也不会用非纯前端的。你看我不一样在好好的写前端吗（尽管没有开源）？
我觉得至少可以分支一个branch改造起来，然后吸纳更多感兴趣的人。毕竟纯前端比非纯前端好些多了，肯定人更多一些。
非纯前端在中型项目中，就可以给你带来十倍于纯前端的代码，而且打包后的内容也有臃肿的态势，对于低网络玩家极其不友好。
***
SVG生成器应该被按图拆分，并对内容进行大重构。
模板内容不用管，只是我认为因该将他更改为存储在后端的一大堆JSON文件。

**Comment by XHG78999** [comment]
另外说一声，在手机上使用会缺字体.....

**Comment by thekingofcity** [comment]
Hi XHG78999, great to hear your suggestion. We do have a stage where a pure front end like jQuery is used.

https://github.com/wongchito/RailMapGenerator/blob/7342b3e273492adfc3eb9c16c7b385218f5553dc/src/index.ts

We upgrade it to React as @wongchito points out and I personally have no framework preference. A handy one that can help the work done would suffice. But changing a framework from where we have now seems not necessary as both of us want to improve the user experience by adding new features and thus have no time in changing this. BTW, I do believe more developers use React, Angular, and Vue than those who don't.

Thanks for your advice and it would be great to see a pure front end from your fork.

**Comment by XHG78999** [comment]
我今天试了一下React的代码风格，发现可以使用相似的polyfill实现几乎无缝的迁移。所以严格意义上来讲，改造起来也不是太难。等我把手头的Proxypool写完了，我就会在fork中使用一个稳定版来自己重写一遍。
谢谢你们的支持。

**Comment by XHG78999** [comment]
我现在已经把这个项目优先级提高了，现在我手头已经在做了，基于v3.4的版本（因为没有被拆分）。
_另外感谢一下NodeJS的`typescript`模块帮我省去了许多麻烦。_
现在我在用MDUI做大致的样子（没有实质功能），为了实现require polyfill的作用我甚至还搭了个Python的小服务器，现在展示一下：
![image](https://user-images.githubusercontent.com/53939187/145710312-ae933301-0bee-48e9-bd78-9ec3598dc05d.png)

**Comment by wongchito** [comment]
> 另外说一声，在手机上使用会缺字体.....

請問是在哪種風格下出現字型缺失呢？

**Comment by XHG78999** [comment]
shmetro 中英文均缺

**Comment by thekingofcity** [comment]
话说我也不是很清楚上海地铁的字体，所以就使用了默认的黑体，如果有了解的话让我换掉就最好了

**Comment by XHG78999** [comment]
> 话说我也不是很清楚上海地铁的字体，所以就使用了默认的黑体，如果有了解的话让我换掉就最好了

的确官方这是默认的黑体，不过手机上没有

**Comment by XHG78999** [comment]
I am trying to do a first new feature in this project, and then I know the non-pure-front-end frame decides many easy things. I know why you use React now.
Thanks for supporting.
Please take an wontfix to the issue. I am closing it.

**Comment by thekingofcity** [comment]
That's what we've been telling from the beginning. Great to hear you get the idea.
