### ISSUE TITLE
我想增加广州地铁13号线及18号线模板

### ISSUE THREAD

**Issue by Dingdong2334** [wongchito/RailMapGenerator#205]
[广州地铁13号线及18号线.zip](https://github.com/wongchito/RailMapGenerator/files/7697016/13.18.zip)
😁

**Comment by thekingofcity** [comment]
Would you like to merge or let me do this job? @wongchito

**Comment by wongchito** [comment]
> Would you like to merge or let me do this job? @wongchito 

I can handle this on Monday. Thanks @thekingofcity

**Comment by wongchito** [comment]
Added. Thanks Dingdong2334!
