### ISSUE TITLE
程序非常好，用广州地铁的模板制作的郑州地铁模板

### ISSUE THREAD

**Issue by C1P918R** [wongchito/RailMapGenerator#210]
[郑州地铁.zip](https://github.com/wongchito/RailMapGenerator/files/7774276/default.zip)

**Comment by thekingofcity** [comment]
谢谢您的支持与鼓励，我们将在之后的一个月中将此模板合入项目，感谢您的耐心等待

**Comment by C1P918R** [comment]
[14号线.json.zip](https://github.com/wongchito/RailMapGenerator/files/7787249/14.json.zip)
郑州地铁14号线更正，查收一下

**Comment by thekingofcity** [comment]
Hi, preparing the line name according to the [Wiki](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates#line-templates) will greatly speed up the merging process.

```
shmetro: [
    {
        filename: 'sh1',
        name: {
            en: 'Line 1',
            'zh-Hans': '1号线',
            'zh-Hant': '1號線',
        },
    },
    {
        filename: 'sh2',
        name: {
            en: 'Line 2',
            'zh-Hans': '2号线',
            'zh-Hant': '2號線',
        },
    },
    ...
],
```

**Comment by thekingofcity** [comment]
嗨，数据合入与 c807db5，更新于 3.10.34。

顺带一提郑州地铁的标志色尚未添加入数据库中，您也可以参考[此教程](https://github.com/wongchito/RailMapGenerator/wiki/How-to-add-color-palette-and-line-templates)提交数据。

**Comment by linchen1965** [comment]
<img width="517" alt="1643274678(1)" src="https://user-images.githubusercontent.com/92020676/151327981-b1dc4aca-fb74-40cb-af78-68dd55661845.png">
![image](https://user-images.githubusercontent.com/92020676/151328814-6357e827-c6bb-460e-8480-78f356c372a9.png)

郑州地铁各线路标志色（直接由郑州地铁官网提取）
1号线：D20200
2号线：D28F00
3号线：CB5100
4号线：3792D6
5号线：25AC74
城郊线：828C47
14号线：844F7C

**Comment by linchen1965** [comment]
![image](https://user-images.githubusercontent.com/92020676/151328951-d99aae8c-532c-4f56-804d-fc4e48cb78e3.png)

![A7T)NR237KB1C4Y0 EXT_S4](https://user-images.githubusercontent.com/92020676/151329009-64f75be1-60f5-4431-ba4e-5f5f0e1be965.png)
郑州地铁各线路标志色（直接由郑州地铁官网提取）
1号线：D20200
2号线：D28F00
3号线：CB5100
4号线：3792D6
5号线：25AC74
城郊线：828C47
14号线：844F7C

**Comment by linchen1965** [comment]
补充：郑州地铁城郊县其实本质上是9号线一期，添加进色板的时候可以直接标记为9号线

**Comment by linchen1965** [comment]
补充：郑州地铁城郊线其实本质上是9号线一期，添加进色板的时候可以直接标记为9号线
<img width="318" alt="1643275638(1)" src="https://user-images.githubusercontent.com/92020676/151330612-6045e839-25a2-4598-9cf0-105978df04e1.png">

**Comment by thekingofcity** [comment]
@linchen1965 How about opening the palettes in `railmapgen/rmg-palette` and opening a new template update issue here?

**Comment by linchen1965** [comment]
> @linchen1965 How about opening the palettes in `railmapgen/rmg-palette` and opening a new template update issue here?

OK, I'll update it with a txt file.

**Comment by C1P918R** [comment]
[3号线.json.zip](https://github.com/wongchito/RailMapGenerator/files/7965236/3.json.zip)
郑州地铁三号线二期营岗站后续4个车站名称有误，等待官方发布。
上面是郑州地铁3号线一期的线路图

**Comment by C1P918R** [comment]
[郑州地铁2:9号线.zip](https://github.com/wongchito/RailMapGenerator/files/7965257/2.9.zip)
2号线和城郊线线路图由原来的合并已经拆分

**Comment by C1P918R** [comment]
[3号线.json.zip](https://github.com/wongchito/RailMapGenerator/files/7965259/3.json.zip)
3号线潮河桥至南曹耿庄站名称有误，具体名称等待官方发布，现已更正

**Comment by thekingofcity** [comment]
嗨，如果需要更新或更正模板，请配上更新的消息源和新的存档文件打开一个新的issue
