### ISSUE TITLE
佛山二号线现已开通  广州地铁21号线“大观南路”站已经撤销快车

### ISSUE THREAD

**Issue by Dingdong2334** [wongchito/RailMapGenerator#214]
佛山二号线现已开通  广州地铁21号线“大观南路”站已经撤销快车
由于疫情，无法到佛山拍摄照片
![微信图片_20220102101114](https://user-images.githubusercontent.com/79365860/147864244-67056b2f-8251-4899-ac73-01bde7bb4f1b.jpg)
![微信图片_20220102101126](https://user-images.githubusercontent.com/79365860/147864246-5f1ee21c-c21c-40e4-b618-3561dc6a0730.jpg)

下面是网络图片
![image](https://user-images.githubusercontent.com/79365860/147864278-a537cc8d-9c40-41d8-9f70-152add4b9fdd.png)

祝您新年快乐

**Comment by wongchito** [comment]
感謝提交Issue，該問題已在3.10.31版本中修復。多謝閣下的支持。
