### ISSUE TITLE
Adding color palettes of Lima and Guadalajara

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#216]
[guadalajara.txt](https://github.com/wongchito/RailMapGenerator/files/7837466/guadalajara.txt)
[lima.txt](https://github.com/wongchito/RailMapGenerator/files/7837467/lima.txt)
Adding color palettes of Lima and Guadalajara

**Comment by linchen1965** [comment]
[lima2.txt](https://github.com/wongchito/RailMapGenerator/files/7852252/lima2.txt)
[guadalajara2.txt](https://github.com/wongchito/RailMapGenerator/files/7852253/guadalajara2.txt)
[Gothenburg.txt](https://github.com/wongchito/RailMapGenerator/files/7852566/Gothenburg.txt)
New versions of Lima and Guadalajara palettes. Added a new palette of Gothenburg

**Comment by thekingofcity** [comment]
Hi, as rmg palettes have been moved to a separate repository, please track the progress at railmapgen/rmg-palette#10

**Comment by thekingofcity** [comment]
Thank you for your contribution. They are updated in d8f5f3c and released in 3.11.1
