### ISSUE TITLE
批量导出生成的图片

### ISSUE THREAD

**Issue by jonathanqwq** [wongchito/RailMapGenerator#218]
如题

**Comment by thekingofcity** [comment]
嗨，这个功能在使用时有什么问题吗？

**Comment by jonathanqwq** [comment]
就比如说我会把这些照片导入到minecraft中，就得一个一个导出啊





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月14日(星期五) 上午9:29
收件人: ***@***.***&gt;; 
抄送: "Jonathan ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wongchito/RailMapGenerator] 批量导出生成的图片 (Issue #218)





 
嗨，这个功能在使用时有什么问题吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thekingofcity** [comment]
嗨，我们在 #125 中添加了此功能，发布于去年11月底，在使用时遇到了什么困难呢？

> Latest UI. This PR could be merged/squashed right now.
> 
> ![image](https://user-images.githubusercontent.com/3353040/141476481-53f88fc9-4f1d-491e-9dd5-799a0b0ca2e4.png)

_Originally posted by @thekingofcity in https://github.com/wongchito/RailMapGenerator/issues/160#issuecomment-967131502_

**Comment by jonathanqwq** [comment]
sorry我的软件貌似是旧版的
我要更新下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wongchito/RailMapGenerator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月14日(星期五) 下午4:56
***@***.***&gt;;
抄送:&nbsp;"Jonathan ***@***.******@***.***&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 批量导出生成的图片 (Issue #218)





 
嗨，我们在 #125 中添加了此功能，发布于去年11月底，在使用时遇到了什么困难呢？
  
Latest UI. This PR could be merged/squashed right now.
 

  
Originally posted by @thekingofcity in #160 (comment)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thekingofcity** [comment]
线上最新是`3.10.33`，离线安装包是`3.10.29`，如果更新后没有问题可以关闭issue 😀
