### ISSUE TITLE
昆明地铁颜色和线路模版

### ISSUE THREAD

**Issue by 52PD** [wongchito/RailMapGenerator#222]
[Kunming Metro Line Template.zip](https://github.com/wongchito/RailMapGenerator/files/7907840/Kunming.Metro.Line.Template.zip)

线路名字和线路颜色的文件在下面：
[Kunming Metro Line Name.txt](https://github.com/wongchito/RailMapGenerator/files/7907845/Kunming.Metro.Line.Name.txt)
[Kunming Metro Color Palette.txt](https://github.com/wongchito/RailMapGenerator/files/7907846/Kunming.Metro.Color.Palette.txt)

**Comment by 52PD** [comment]
然后稍微说一下1号线跟2号线的模版。
目前昆明地铁因为1号线2期（1号线北段线路）和2号线2期（2号线南段线路）还在建设中，故1号线跟2号线是贯通运营的，但由于1/2号线并没有统一用同一线路颜色（在官方线路图上1号线区间仍然为红色，而2号线区间仍然为蓝色），再加上目前程序没法给同一条线路做两个不同颜色，所以我就退而求其次把两条线路分开来做了。

**Comment by thekingofcity** [comment]
嗨，感谢您的首次贡献，在检察后我们将合入这些资源

**Comment by 52PD** [comment]
> 嗨，感谢您的首次贡献，在检察后我们将合入这些资源

好的，谢谢！😄

**Comment by thekingofcity** [comment]
@wongchito

How about taking this issue and getting familiar with the new railmapgen/rmg-palettes when it is ready?

**Comment by thekingofcity** [comment]
嗨，数据更新于 df7519f872057e69c77ab2e411153835bc55bb0e，发布于3.11.3

感谢您对项目的支持与贡献，现已将您添加入贡献者名单中 🎉

![image](https://user-images.githubusercontent.com/3353040/150777040-70c0aeff-57c4-4d50-91cc-185620cdb25f.png)
