### ISSUE TITLE
成都地铁部分线路色错误

### ISSUE THREAD

**Issue by GrassRabbit1410** [wongchito/RailMapGenerator#228]
11号线和16号线线路色反了，14号线和17号线线路色反了
数据源：DB 5101/T 9-2018 附录B
![微信图片_20220126132737](https://user-images.githubusercontent.com/94828677/151109232-047132a6-b5e8-49d1-89b1-bf08d4f8283d.jpg)

**Comment by XHG78999** [comment]
谢谢您的提醒，我们会在后期审核色卡和模板时统一处理。
或者您可以根据wiki中的教程帮助我们修复。

**Comment by thekingofcity** [comment]
已更新入资源库中，等待下一次发布时会自动更新此城市。谢谢您的贡献与支持。
