### ISSUE TITLE
Some problems about switching Languages

### ISSUE THREAD

**Issue by tianxiu111111** [wongchito/RailMapGenerator#23]
@thekingofcity Once, I accidentally switched simplified Chinese to English in the language interface, and then I can't change it back by pressing Chinese again. Please pay attention

**Comment by thekingofcity** [comment]
可以有截图和浏览器开发者工具中的console吗？除上海风外我不是很熟

@wongchito 方便跟进一下吗

**Comment by wongchito** [comment]
@tianxiu111111 I've tested on several platforms but didn't encounter this problem. Could you please provide further information about this issue. At the same time, you may have to check your internet connection since translation scripts are loaded asynchronously.

**Comment by wongchito** [comment]
I've found out the bugs causing this issue. It would be solved recently. Thanks again for reporting.

**Comment by wongchito** [comment]
This issue has been fixed in Version 3.2.
