### ISSUE TITLE
Setup CI to auto check linting issues

### ISSUE THREAD

**Issue by wongchito** [wongchito/RailMapGenerator#232]
- [x] Add rule to `.eslintrc`: prettier: warn
- [x] Fix prettier warning in current master
- [x] Cherry pick fixes to V5
- [x] Change to error level for each PR
- [x] Check linting issues for each PR

**Comment by wongchito** [comment]
@thekingofcity This issue requires your help to format the shmetro-related code. Thanks!

**Comment by thekingofcity** [comment]
Let me fix Shmetro tomorrow

**Comment by thekingofcity** [comment]
Shmetro should be aligned with ESlint.

For anyone who faces a weird `value` insertion in formatting may restart the VSCode as suggested by this StackOverflow.
https://stackoverflow.com/questions/70564950/vscode-prettier-adds-value-to-imports-in-typescript-react
