### ISSUE TITLE
Line colors of Shenzhen metro changed

### ISSUE THREAD

**Issue by linchen1965** [wongchito/RailMapGenerator#250]
Official Website: htps://www.szmc.net/map/
Line color of Shenzhen metro Line 20 was changed. The color code of line 20 should be 9CD0CB.
For line 14 and line 16. The line color codes should be F2C75C and 1E22AA (data from Wikipedia)

**Comment by XHG78999** [comment]
So would you like to fix it by wiki tutorial?

**Comment by thekingofcity** [comment]
I think all the palettes changes should be in railmapgen/rmg-palette. We should update it there.

**Comment by linchen1965** [comment]
> So would you like to fix it by wiki tutorial?

I would like to fix it but actually I don't really know how to fix it by wiki tutorial.

**Comment by XHG78999** [comment]
> > So would you like to fix it by wiki tutorial?
> 
> I would like to fix it but actually I don't really know how to fix it by wiki tutorial.

Also, now palettes moved to rmg-palette. You can go to https://github.com/railmapgen/rmg-palette/wiki/How-to-add-color-palette to know.

**Comment by XHG78999** [comment]
OK, Now I open a pull request to rmg-palette. @thekingofcity please accept it and commit to main repo. Also let me assign this and close it.

**Comment by thekingofcity** [comment]
Hi, @XHG78999 it's been a month. How does the change going?

**Comment by XHG78999** [comment]
> Hi, @XHG78999 it's been a month. How does this work going?

..... [擦汗]Sorry, I forget to pin it so i forget to do it. Now I open a pull request.

**Comment by wongchito** [comment]
Fixed in rmg-palette-resources@0.3.2
