### ISSUE TITLE
TNH1、TGM1

### ISSUE THREAD

**Issue by 20110620bobby** [wongchito/RailMapGenerator#258]
佛山TNH1南海有轨一号线配色与TGM1高明有轨一号线配色反了

**Comment by wongchito** [comment]
多謝指正！該issue將移至@railmapgen/rmg-palette繼續討論。

**Comment by wongchito** [comment]
Fixed https://github.com/railmapgen/rmg-palette/commit/1821c757c66f1d20637a2a61fda1786bf08f5ca7
