### ISSUE TITLE
[猜测]广州地铁十一号线（环线）线路图

### ISSUE THREAD

**Issue by Dingdong2334** [wongchito/RailMapGenerator#259]
![gzmetro11](https://user-images.githubusercontent.com/79365860/154681537-7909172b-460f-401c-a374-40c0aa54e232.png)

**非官方。**
**以上车站名称仅为工程暂定名称，标准站名应以市政府批准公布为准。**
**并非规划。**

**Comment by Dingdong2334** [comment]
> 抱歉，
> 
> 我们不允许任何猜测和非官方的线路图。
> 
> 感谢您对RailMapGenerator的支持。

好的！
我是想等待官方线路图出来后看一下我的猜测是否正确。

**Comment by 52PD** [comment]
> 抱歉，
> 
> 我们不允许任何猜测和非官方的线路图。
> 
> 感谢您对RailMapGenerator的支持。

啊这，那我之前提交（而且已经汇入项目了）的昆明地铁5号线应该怎么算啊😂（昆明5号线倒是已经确认今年4月正式对外开放了，而且站名、换乘和颜色也都是全部定下来了的，唯独缺少官方的车站英文名）

**Comment by XHG78999** [comment]
> > 抱歉，
> > 
> > 我们不允许任何猜测和非官方的线路图。
> > 
> > 感谢您对RailMapGenerator的支持。
> 
> 啊这，那我之前提交（而且已经汇入项目了）的昆明地铁5号线应该怎么算啊😂（昆明5号线倒是已经确认今年4月正式对外开放了，而且站名、换乘和颜色也都是全部定下来了的，唯独缺少官方的车站英文名）

。。。这个是wongchito的锅了，忘记查资料校对23333
马上就会删的。

**Comment by 52PD** [comment]
> > > 抱歉，
> > > 我们不允许任何猜测和非官方的线路图。
> > > 感谢您对RailMapGenerator的支持。
> > 
> > 
> > 啊这，那我之前提交（而且已经汇入项目了）的昆明地铁5号线应该怎么算啊😂（昆明5号线倒是已经确认今年4月正式对外开放了，而且站名、换乘和颜色也都是全部定下来了的，唯独缺少官方的车站英文名）
> 
> 。。。这个是wongchito的锅了，忘记查资料校对23333 马上就会删的。

OK👌

**Comment by wongchito** [comment]
你好 @Dingdong2334 ，

廣州地鐵風格暫不支援環線，詳見#24 。惟於第5代RMG中上海地鐵風格提供環線之功能，閣下可於上海風格中設定環線之相關參數，待廣州地鐵11號線開通及RMG正式支援廣州地鐵風格之環線後，直接使用該JSON檔案。多謝閣下的支持！

**Comment by Dingdong2334** [comment]
好的，谢谢您！



在 2022-04-01 01:41:33，"Chito Wong" ***@***.***> 写道：

你好 @Dingdong2334 ，

廣州地鐵風格暫不支援環線，詳見#24 。惟於第5代RMG中上海地鐵風格提供環線之功能，閣下可於上海風格中設定環線之相關參數，待廣州地鐵11號線開通及RMG正式支援廣州地鐵風格之環線後，直接使用該JSON檔案。多謝閣下的支持！
