### ISSUE TITLE
下载线路图后照片模糊

### ISSUE THREAD

**Issue by scholar1922** [wongchito/RailMapGenerator#26]
360下载图片后放大来看会很模糊，Firefox甚至下载后无法显示，望解决，谢谢

**Comment by PassionPenguin** [comment]
？什么图片
什么分辨率：）

**Comment by PassionPenguin** [comment]
pls provide a detailed info for your issue~ thx

**Comment by scholar1922** [comment]
线路图

**Comment by PassionPenguin** [comment]
你可以使用scale功能调整分辨率的

**Comment by PassionPenguin** [comment]
麻烦用邮件或其它方式，将您的保存的图片发送一下：）
无法了解到您的具体状况

**Comment by wongchito** [comment]
> 360下载图片后放大来看会很模糊
Please select an appropriate 'scale' in the export dialogue. 

> Firefox甚至下载后无法显示
Thanks for reporting this issue.

**Comment by scholar1922** [comment]
调整分辨率后稍微好一点了，谢谢

**Comment by scholar1922** [comment]
> Please select an appropriate 'scale' in the export dialogue.

Sorry,This is my first time to make a feedback on this website.I don't know where the "scale" button is.Could you tell me how to select the scale?

**Comment by PassionPenguin** [comment]
hmm就是在导出的那里啊...

**Comment by PassionPenguin** [comment]
导出界面从上往下数第三个选项～

**Comment by wongchito** [comment]
@scholar1922 

Here you go. 
<img width="256" alt="Screenshot 2020-03-30 at 21 57 54" src="https://user-images.githubusercontent.com/9390786/77920883-9ca4d180-72d1-11ea-847f-96279ee389b5.png">

**Comment by PassionPenguin** [comment]
also, next time adding files to issues may be better to make your friends be able to quick get in touch with your problem~
the files toggle is here~

<img width="688" alt="截屏2020-03-30 下午10 00 12" src="https://user-images.githubusercontent.com/41184947/77921120-ec839880-72d1-11ea-951f-5e79c05b0ccf.png">

**Comment by scholar1922** [comment]
-

> 
> 
> also, next time adding files to issues may be better to make your friends be able to quick get in touch with your problem~
> the files toggle is here~
> 
> <img alt="截屏2020-03-30 下午10 00 12" width="688" src="https://user-images.githubusercontent.com/41184947/77921120-ec839880-72d1-11ea-951f-5e79c05b0ccf.png">

I could not open it

**Comment by scholar1922** [comment]
> 
> 
> @scholar1922 There you go.
> <img alt="Screenshot 2020-03-30 at 21 57 54" width="256" src="https://user-images.githubusercontent.com/9390786/77920883-9ca4d180-72d1-11ea-847f-96279ee389b5.png">

My issue has been solved and thank you for helping me solve it.

**Comment by wongchito** [comment]
@scholar1922 My issue has been solved and thank you for helping me solve it.

Please leave this open until the PNG export issue in Firefox is solved.

**Comment by scholar1922** [comment]
> 
> 
> @scholar1922 My issue has been solved and thank you for helping me solve it.
> 
> Please leave this open until the PNG export issue in Firefox is solved.

Ok

**Comment by scholar1922** [comment]
> 
> 
> also, next time adding files to issues may be better to make your friends be able to quick get in touch with your problem~
> the files toggle is here~
> 
> <img alt="截屏2020-03-30 下午10 00 12" width="688" src="https://user-images.githubusercontent.com/41184947/77921120-ec839880-72d1-11ea-951f-5e79c05b0ccf.png">

我理解错了scale 的意思，我以为是其他问题后的那些"QUESTION""ENHANCEMENT"的标签，抱歉，打扰你了
