### ISSUE TITLE
关于昆明地铁模版的一些问题

### ISSUE THREAD

**Issue by 52PD** [wongchito/RailMapGenerator#261]
之前看到@wongchito 在https://github.com/wongchito/RailMapGenerator/issues/241#issuecomment-1041814309 提到佛山地铁3号线还没开通的原因会暂缓加入。
所以昆明地铁5号线（目前没开通，预计今年内开通）要不要在下次更新中暂时从项目中移除掉？（这个确实算是我的失误了，毕竟佛山3号线这种未开通线路都考虑暂缓加入了，昆明5号线这种同样未开通的线路反而加入了项目确实挺不合适的）

顺带微调了一下其余5条线（1/2/3/4/6号线）的图（去掉了5号线）：
[Kunming Metro Line Template V2 （without Line 5).zip](https://github.com/wongchito/RailMapGenerator/files/8102661/Kunming.Metro.Line.Template.V2.without.Line.5.zip)

然后想问一下，以后有没有可能在项目中加入一线双色这种奇怪设定啊（参考下图，图中的线路图中右侧红色区间为1号线，左侧蓝色区间为2号线）
![1_6af81098c01f4ee3acab2d97634d6c5d](https://user-images.githubusercontent.com/98044618/154812137-6a0ec634-3900-4e25-8625-dd9e565dc4c2.jpg)
毕竟在现在没有双色线路的情况下要还原现在官方的昆明1/2号线贯通线路图确实行不通（ps：昆明官方计划要等1号线北段/2号线南段通车后才分拆两条线路）

**Comment by XHG78999** [comment]
双色大概率不会加入。模板问题吗，移除就可以了，但是现有线路对于在建线路的换乘可以不删，具体看sh模板。

**Comment by 52PD** [comment]
> 双色大概率不会加入。模板问题吗，移除就可以了，但是现有线路对于在建线路的换乘可以不删，具体看sh模板。

OK，谢谢！
那移除5号线模版就麻烦你们了🙏！

**Comment by linchen1965** [comment]
昆明地铁5号线据说是4月30日开通，距离开通时间也不远了，其实没有必要移除模版吧？

**Comment by 52PD** [comment]
> 昆明地铁5号线据说是4月30日开通，距离开通时间也不远了，其实没有必要移除模版吧？

主要是想着目前5号线各站英文名是不知道的（也就是5号线有些车站的英文名很可能不是官方名字）😂，
而且 @XHG78999 也在https://github.com/wongchito/RailMapGenerator/issues/259#issuecomment-1045531480 说了不能上猜测和非官方图

**Comment by XHG78999** [comment]
> 昆明地铁5号线据说是4月30日开通，距离开通时间也不远了，其实没有必要移除模版吧？

去年10月就一直有人嚷嚷加入自己制作的上海地铁模板，里面有14，18全线，可是14和18剩一直到12月31日开通才加入。。

**Comment by thekingofcity** [comment]
😂大家说的都对，但是马上就要开通了我们就不移出再移入了。

我们「原則上只加入已正式開通的線路」。

**Comment by XHG78999** [comment]
az，那就弄个hold。@thekingofcity

**Comment by 52PD** [comment]
> 😂大家说的都对，但是马上就要开通了我们就不移出再移入了。如果有错误的话就到时再提issue修改吧。
> 
> 我们「原則上只加入已正式開通的線路」。但如果因为各种原因没有检查出来或意外导致线路添加的话，我们也只会到有人提出来后再移除。

好的，谢谢
