### ISSUE TITLE
沈阳地铁线路颜色

### ISSUE THREAD

**Issue by xxcpeter** [wongchito/RailMapGenerator#263]
希望增加沈阳地铁线路颜色，谢谢。目前官网没有标准色号，只有已批复线路图（运营和在建），目前采用对官网线路图进行取色提取出色号。附文件
[SYmetro-color-palette.txt](https://github.com/wongchito/RailMapGenerator/files/8104300/SYmetro-color-palette.txt)

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的贡献与支持。稍后我们会将此数据合入项目中，并添加您的头像与昵称到info面板，谢谢🎉

**Comment by thekingofcity** [comment]
已添加入资源库中，等待下一次发布时会自动更新此城市。谢谢您的贡献与支持。
