### ISSUE TITLE
为什么我无法下载已经制作完毕的线路图？ Why I can't download the Rail Map that I finished editing?

### ISSUE THREAD

**Issue by Mark-MTR** [wongchito/RailMapGenerator#268]
为什么我无法下载已经制作完毕的线路图？ 一定要截图吗？这样会看不清楚。
Why I can't download the Rail Map that I finished editing? Do I must to take a screenshot? That would be not clear.

**Comment by thekingofcity** [comment]
本项目确有提供下载线路图为svg和png图片格式的功能。如果您在使用过程中遇到错误，请描述什么样的操作导致了什么样的错误，并报告您的浏览器/操作系统/项目版本等信息，谢谢。
