### ISSUE TITLE
关于安卓端（手机）的显示bug～Display bug of Android terminal (mobile phone)

### ISSUE THREAD

**Issue by OrdinaryRUNYING** [wongchito/RailMapGenerator#276]
1.（bug）部分安卓端在V5版本UI内容显示不全以至于无法关闭部分编辑页面
![Screenshot_20220313_122641](https://user-images.githubusercontent.com/101465504/158045126-eb7d62a5-5c92-4f78-b8e2-c0c5965f8496.jpg)
![Screenshot_20220313_122545](https://user-images.githubusercontent.com/101465504/158045127-b9356401-27c8-4be9-9c72-2582aa5a6c70.jpg)
2.（BUG）V5中上海版共线门板图未更新（可能应该是还在开发吧）
3.（bug）大部分未完成翻译（应该是刚刚开始测试没这么快更新，相信正式版应该会增加的）

1. (Bug) the UI content of some Android terminals in V5 is not fully displayed, so that some editing pages cannot be closed
2. (Bug) the common line door panel drawing of Shanghai version in V5 has not been updated (may be still under development) 
3 (Bug) most of the translations have not been completed (May be because the test has just started and the update is not so timely. I think itwill be added in the official version.)
Most English translations come from Baidu.

**Comment by XHG78999** [comment]
1.的确，RMG的UI设计有些对超小屏不友好，不过本身他是给电脑用户的。我们以后会考虑为小屏提供单独UI或者禁止小屏使用RMG。
2.共线门板图刚更新.......可能还没push上去，这点我要咨询一下@thekingofcity
3.的确，我们目前V5的重心在代码和两大究极新功能上，目前是只要有English能用就可以，发布前我们会添加相关翻译

谢谢您对我们的支持。

**Comment by OrdinaryRUNYING** [comment]
> 1.的确，RMG的UI设计有些对超小屏不友好，不过本身他是给电脑用户的。我们以后会考虑为小屏提供单独UI或者禁止小屏使用RMG。 2.共线门板图刚更新.......可能还没push上去，这点我要咨询一下@thekingofcity 3.的确，我们目前V5的重心在代码和两大究极新功能上，目前是只要有English能用就可以，发布前我们会添加相关翻译
> 
> 谢谢您对我们的支持。

谢谢～
如果手机端取消使用的话会不会考虑手机端仍然使用旧版（V3版）呢

**Comment by thekingofcity** [comment]
> 1.（bug）部分安卓端在V5版本UI内容显示不全以至于无法关闭部分编辑页面
> (Bug) the UI content of some Android terminals in V5 is not fully displayed, so that some editing pages cannot be closed

我们会保证UI在发布时会在移动设备上正确显示，当然项目仍然是以desktop为目标来开发的。
We will ensure the correctness of UI in the public release, but do keep in mind this project is made for the desktop environment.

> 2.（BUG）V5中上海版共线门板图未更新（可能应该是还在开发吧）
> 2. (Bug) the common line door panel drawing of Shanghai version in V5 has not been updated (may be still under development)

这个应该可以被确认为不被支持的功能了，简单来说是由于之前的indoor实现中使用了mtr的线路画法实现，将其改变为上海风格的门板图几乎不可能。所以在门板图被重写前应该是无法看到共线了。虽然我也很讨厌不完美，但受限于精力和时间大抵仅能如此了。🙃
This will be an unsupported feature for a long time. The reason for short is the reuse of an MTR implementation. Although shortens the development cycle, it is really difficult to comply with the coline layout. So no coline in indoor. 🙃

> 3.（bug）大部分未完成翻译（应该是刚刚开始测试没这么快更新，相信正式版应该会增加的）
> 3. (Bug) most of the translations have not been completed (May be because the test has just started and the update is not so timely. I think itwill be added in the official version.)

我们会在发布前补齐所有翻译文本，所以坐和放宽 🤣
We will a through i18n translation before public release. So sit back and relax.
