### ISSUE TITLE
Template of Beijing Subway Line 2(Loop)

### ISSUE THREAD

**Issue by AnDanJuneUnderline** [wongchito/RailMapGenerator#277]
Made with https://wongchito.github.io/uat-rail-map-generator/.
[Beijing Subway Line 2.zip](https://github.com/wongchito/RailMapGenerator/files/8241823/Beijing.Subway.Line.2.zip)
The English translation of Beijing Subway station name has been changed. All of the letter "a" changed to "α", like Chinese pinyin.

**Comment by thekingofcity** [comment]
They are updated and will be released to UAT in the next build. Thanks for your contribution! 🎉

**Comment by AnDanJuneUnderline** [comment]
OK, I changed the json file after reading #280 .
Here it is.
[l2.zip](https://github.com/wongchito/RailMapGenerator/files/8250074/l2.zip)

**Comment by thekingofcity** [comment]
Hi, they are tweaked in the commit. Should be pretty here.
