### ISSUE TITLE
关于上海地铁风格下的两个问题以及三个建议

### ISSUE THREAD

**Issue by Kurasu-SShirouto** [wongchito/RailMapGenerator#29]
1.在添加出站换乘线路后，删除该出站换乘线路，"换乘仅限公共交通卡"不会消失
2.换乘线路下面那根黑线没有显示？
3.不知道有没有添加磁浮线图标以及“换乘磁浮线“字样的打算
4.不知道有没有添加环线的打算
5.部分车站 例如13号线全线车站 的类似终点站牌的站牌上 是会显示当前处于几站台的 大概格式是"←往张江路 ④站台 13号线"这样的 不知道能不能开一个相关设定的选项

**Comment by thekingofcity** [comment]
1,2应该会在近期修复
3和5在mtr中都有类似实现, 不复杂的话会考虑添加, 不过目前计划在大站车之后
4请见#24

十分感谢感谢您的关注与建议, 但由于精力有限我可能要到夏天才能添加更多功能了

**Comment by thekingofcity** [comment]
2已修复 34d900c

**Comment by thekingofcity** [comment]
Maglev in 40988f7
