### ISSUE TITLE
【bug？】V5版本中的上海地铁风格显示不了部分大站车停靠站点

### ISSUE THREAD

**Issue by TNLHK** [wongchito/RailMapGenerator#292]
如题，在V5版本中用上海地铁风格显示不了部分大站车停靠站点（如图所示），不知道是不是bug。
![bug](https://user-images.githubusercontent.com/81743463/159425509-e3bb5d12-a329-48d3-a058-b8e7058b4a4c.png)
![bug2](https://user-images.githubusercontent.com/81743463/159425501-42d547ba-32ad-4274-a632-312737ccd31b.png)

**Comment by XHG78999** [comment]
Thinks the coline break this. Because I didn't take something in this, i am going to ask @thekingofcity.

**Comment by thekingofcity** [comment]
方便分享一下下面的json存档吗？

**Comment by TNLHK** [comment]
> 方便分享一下下面的json存档吗？

第一张图直接加载上海地铁16号线的模板就行了
[CRT4.zip](https://github.com/wongchito/RailMapGenerator/files/8322072/CRT4.zip) 第二张图的存档

**Comment by thekingofcity** [comment]
修复了一个貌似在merge时丢失的path资源，谢谢指出。
