### ISSUE TITLE
Electron build shows a black screen

### ISSUE THREAD

**Issue by MasterYuan418** [wongchito/RailMapGenerator#294]
![图片](https://user-images.githubusercontent.com/58651976/159612152-2f5ab964-057e-4916-9e57-45e4bd337942.png)
如图，使用了最新的离线版（版本`3.10.29`），但打开窗口后白屏。
![图片](https://user-images.githubusercontent.com/58651976/159612222-55487302-7259-413f-9791-5c1936a7f70e.png)
控制台报错如上图
![图片](https://user-images.githubusercontent.com/58651976/159612399-53c091b3-e9c3-4713-a183-558382e26b6c.png)
在线版可以正常打开。
环境信息：
```
OS: MS Windows 10 Build 19043
CPU: AMD R5-3600
RAM: 16GB DDR4
```

**Comment by XHG78999** [comment]
好像是翻译没有打包进去。

**Comment by thekingofcity** [comment]
此问题可复现，当我们正在修复时欢迎你访问在线页面使用，对此带来的不便深表歉意。

**Comment by thekingofcity** [comment]
This should be fixed in the [RMG-3.12.2 Release](https://github.com/wongchito/RailMapGenerator/releases/tag/3.12.2), you're welcome to have a try.
