### ISSUE TITLE
支线怎么添加？

### ISSUE THREAD

**Issue by moerail** [wongchito/RailMapGenerator#3]
如题，只能在模板里面选带支线的模板然后更改车站，无法手动添加支线。

**Comment by Rongronggg9** [comment]
![Screenshot_20191225_110117_com android chrome](https://user-images.githubusercontent.com/15956627/71430320-fcee0b00-2705-11ea-8d4a-86be5e60adb8.png)
您不能在线路开头前方或线路末尾后方增加支线，请在中间站点或线路开头后方或线路末尾前方添加支线。
