### ISSUE TITLE
上海地铁未来规划（颜色未知）

### ISSUE THREAD

**Issue by Yexiaowei11** [wongchito/RailMapGenerator#303]
28号线：周邓公路-年家浜东路-年家浜路-东佳路-陈行公路-浦锦路-联航路-元江路
29号线：美丹路-美丰路-月罗公路-富长路-大康路-高平路-运城路-宜川路-中潭路-昌化路
30号线：高科东路-高科中路-高科西路-沪南路
31号线：新川路-城丰路-科农路-康南路-科宛路-卫行西路-御水路-西中路-高青路-陈春东路-陈春路
正在制作中. . .

**Comment by Yexiaowei11** [comment]
上海地铁规划线路

19号线	虹建路站-宝杨路站	      	                         规划中
20号线一期工程	金昌路站-共青森林公园站        规划中
21号线一期工程	川沙路站-东靖路站	         	 规划中
23号线一期工程	闵行开发区站-上海体育场站    规划中
13号线西延伸段	诸光路站-金运路站                  规划中
1号线西延伸段	莘庄站-莘庄火车站                   规划中
机场联络线	        虹桥枢纽-上海东站                   规划中
嘉闵线	                嘉定北站-莘庄北站                   规划中
崇明线	                金吉路站-裕安路站                   规划中

**Comment by Yexiaowei11** [comment]
上海地铁规划线路

19号线 虹建路站-宝杨路站 >>>>>>>>>>>规划中
20号线一期工程 金昌路站-共青森林公园站 >>>>>>>>>>>规划中
21号线一期工程 川沙路站-东靖路站 >>>>>>>>>>>规划中
23号线一期工程 闵行开发区站-上海体育场站 >>>>>>>>>>>规划中
13号线西延伸段 诸光路站-金运路站 >>>>>>>>>>>规划中
1号线西延伸段 莘庄站-莘庄火车站 >>>>>>>>>>>规划中
机场联络线 虹桥枢纽-上海东站 >>>>>>>>>>>规划中
嘉闵线 嘉定北站-莘庄北站 >>>>>>>>>>>规划中
崇明线 金吉路站-裕安路站>>>>>>>>>>> 规划中

**Comment by Yexiaowei11** [comment]
颜色已经正在查找了等我消息~

**Comment by 52PD** [comment]
> 28号线：周邓公路-年家浜东路-年家浜路-东佳路-陈行公路-浦锦路-联航路-元江路
> 29号线：美丹路-美丰路-月罗公路-富长路-大康路-高平路-运城路-宜川路-中潭路-昌化路
> 30号线：高科东路-高科中路-高科西路-沪南路
> 31号线：新川路-城丰路-科农路-康南路-科宛路-卫行西路-御水路-西中路-高青路-陈春东路-陈春路
> 正在制作中. . .

如果是这种没开通的线路建议还是等开通后再提交。未开通或者规划中的线路即使现在提交了开发团队也是不会立即加入项目中的。

具体参考#241 里面制作团队对未开通的佛山地铁3号线的看法。

**Comment by thekingofcity** [comment]
我们不会处理任何尚未通车的线路，感谢您对项目的支持！
