### ISSUE TITLE
Switch RMG V3 gh-pages to wongchito.github.io

### ISSUE THREAD

**Issue by wongchito** [wongchito/RailMapGenerator#305]
- [x] Deploy RMG V3 to wongchito.github.io
- [x] Unpublish wongchito.github.io/RailMapGenerator

**Comment by thekingofcity** [comment]
This marks the start of our V5 release! Cheers🎉

**Comment by wongchito** [comment]
UAT exercise is done. 

GitHub pages for wongchito/uat-rail-map-generator is unpublished
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/9390786/162447293-b6f60def-e4b7-4bc1-a03e-9e441867d9ba.png">

GitHub pages for wongchito/wongchito.github.io is published
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/9390786/162447427-5de67da2-04bc-4c51-890e-29c0b5cdb48a.png">

Can load UAT RMG and handle react-router redirecting correctly
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9390786/162446987-a185e6d7-ae4e-4a41-92f3-b4ec8c2eecc5.png">

**Comment by wongchito** [comment]
Deployed to wongchito.github.io
<img width="997" alt="image" src="https://user-images.githubusercontent.com/9390786/162460599-dcfb6c9c-77bb-4a71-9879-679f58f7c0cd.png">

**Comment by wongchito** [comment]
Unpublished wongchito.github.io/RailMapGenerator
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/9390786/162462069-fab31504-a517-441f-b05e-ca7d288218c8.png">
