### ISSUE TITLE
西安地铁的颜色问题

### ISSUE THREAD

**Issue by 3394946742** [wongchito/RailMapGenerator#35]
西安地铁的颜色有点问题啊
3、5号线淡了
6号线应该是紫色（根据观察，虽然车是蓝色的，但换乘预留明显是紫色
11号线明显是橙色的（而10号线才是当前11号线的颜色）
8号线浓了，应该是橙黄色
建议增加10号线、16号线等获审批的线路
谢谢

**Comment by wongchito** [comment]
Current source of palette:

Line 1-6, 9: Pantone colours from [西安市轨道交通集团's reply to enquiry](http://www.ditiezu.com/thread-668313-1-1.html), transformed to HEX(RGB) with [Pantone Colour Finder](https://www.pantone.com/color-finder). 

Line 14: Pantone colour from [this post](http://www.ditiezu.com/thread-668349-1-1.html), transformed to HEX with Pantone colour finder. 

Line 8 and 11: https://zh.wikipedia.org/wiki/Template:西安地铁颜色

Should you have the latest or more precise colours, please provide the source or link to help us update the palette. Thank you.

**Comment by 3394946742** [comment]
（颜色问题的话，西安地铁这问题好长时间了，颜色非常的混乱）
&nbsp; 但是我建议还是以百度百科、西安地铁官网为准，谢谢
&nbsp;ps：地铁族网站和悦西安都有地铁百年大计的图，也可以适当的加一些线路




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chito Wong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 晚上10:25
收件人:&nbsp;"wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;"Dream丶David"<3394946742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 西安地铁的颜色问题 (#35)





 
Current source of palette:
 
Line 1-6, 9: Pantone colours from 西安市轨道交通集团's reply to enquiry, transformed to HEX(RGB) with Pantone Colour Finder.
 
Line 14: Pantone colour from this post, transformed to HEX with Pantone colour finder.
 
Line 8 and 11: https://zh.wikipedia.org/wiki/Template:西安地铁颜色
 
Should you have the latest or more precise colours, please provide the source or link to help us update the palette. Thank you.

**Comment by wongchito** [comment]
We have guidelines of which kinds of sources of palettes could be used for RMG (#28). 

I have checked [Xi'an Metro Official Website](https://xianrail.com/#/index) but it doesn't seem to provide a PDF version of route map or design standards, while they have replied to enquiry about the palette (see above). So their reply would be the best source. 

You may customise the colours by using the colour picker if you have special needs. Thank you.

**Comment by 3394946742** [comment]
那。。。西安地铁6的官方色确实是紫色啊（但是西安地铁一直在弱化标志色，所以特别混乱，4号线颜色跟5号线老混淆），你们可以标注一下什么的，确实很混乱


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chito Wong"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 中午11:17
收件人:&nbsp;"wongchito/RailMapGenerator"<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;"Dream丶David"<3394946742@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 西安地铁的颜色问题 (#35)





 
We have guidelines of which kinds of sources of palettes could be used for RMG (#28).
 
I have checked Xi'an Metro Official Website but it doesn't seem to provide a PDF version of route map or design standards, while they have replied to enquiry about the palette (see above). So their reply would be the best source.
 
You may customise the colours by using the colour picker if you have special needs. Thank you.
