### ISSUE TITLE
建议：车站名字过长时自动调整字体大小

### ISSUE THREAD

**Issue by BornForFever** [wongchito/RailMapGenerator#36]
比如这张图，几个车站名字都挤到一起了，建议车站名字过长时自动把字体调小。
![批注 2020-04-09 100448](https://user-images.githubusercontent.com/62426149/78850768-97225680-7a4a-11ea-9b9b-cd588118dc24.png)

**Comment by thekingofcity** [comment]
为了保证比例正确, 字体大小不会调整
建议调整宽度以容纳所有文字
