### ISSUE TITLE
Unable to show icons in Chromium Edge Canary

### ISSUE THREAD

**Issue by SZMetr0** [wongchito/RailMapGenerator#47]
It would show the caption of the module directly instead.
Versions 80s-84.0.508.0 affected.
Won't affect Google Chrome Canary 84.0.4143.0.

**Comment by wongchito** [comment]
This issue is discussed [here (Chinese only)](http://www.ditiezu.com/forum.php?mod=redirect&goto=findpost&ptid=659763&pid=11648559).

**Comment by wongchito** [comment]
The Material Icon font has been replaced by self hosted file. 

Closed for no reply for more than a year.
