### ISSUE TITLE
广州地铁7号线和广佛线颜色错误

### ISSUE THREAD

**Issue by Benteds** [wongchito/RailMapGenerator#5]
根据广州地铁官方的新版线路图，7号线和广佛线框儿里的字是黑的，不是白的

**Comment by wongchito** [comment]
**Line 7:**

The info panels of Line 7 and Line 4 (which have been recently updated) show that the foreground colour of Line 7 is white. 

Reference: 
[ [走遍中国]（广州）都市边缘线—不愿离开这片宁静土地For Line 7（50P）](http://www.ditiezu.com/thread-550859-1-1.html)
[  [走遍中国]（广州）寻迹海风—夏日彼端的遥远天空For Line 4（182P）](http://www.ditiezu.com/thread-655515-1-1.html)

**Guangfo Line:**

| Info Panels of | Year of Update | How Guangfo Line is shown | Foreground colour |
| --- | --- | --- | --- |
| Guangfo Line | late 2018 | self | white |
| Line 3 | late 2018 | interchange | white |
| Line 2 | late 2018 | interchange | white |
| Line 8 | late 2019 | interchange | black |
| Line 1 | late 2019 | interchange | black |

The foreground colour of Guangfo Line will remain unchanged until the info panels in the stations of Guangfo Line are updated with a different foreground colour.

**Comment by wongchito** [comment]
Version 2.11 provides new feature of customising colours, including both background and foreground colours of theme or interchanges. You may now use this feature for 'correcting' the foreground colours of Line 7 and Guangfo Line.
