### ISSUE TITLE
How to change font size for high-resolution outputs

### ISSUE THREAD

**Issue by Prurite** [wongchito/RailMapGenerator#52]
When I turn the resolution up, say 2048x512, the text doesn't automatically get larger to fit the increased resolution. So is it possible to control the font size manually, or at least add automatic font size adjustment?

**Comment by wongchito** [comment]
Font sizes are in proportion to the size of the canvas and they cannot be changed separately. 

You may select a larger scale in the export dialogue to generate a higher resolution image.
