### ISSUE TITLE
Can't edit exported svg in Adobe Illustrator or any similar svg editors

### ISSUE THREAD

**Issue by Prurite** [wongchito/RailMapGenerator#53]
All of them either can't open the file correctly, or report that 'Invalid svg file format'. Here's how it looks in AI:
![图片](https://user-images.githubusercontent.com/44775584/88182055-4b469680-cc62-11ea-892a-aa6dc2be3fe5.png)

**Comment by wongchito** [comment]
The SVGs exported are for web use only currently. For more information please refer to #2 .
