### ISSUE TITLE
SITE CLOSED!!!

### ISSUE THREAD

**Issue by maliaoshui** [wongchito/RailMapGenerator#55]
![22A594D4-C5EC-4DEC-8869-CE274382014B](https://user-images.githubusercontent.com/63832863/90001324-e1029e00-dcc3-11ea-9bee-a5abcc19c6fa.png)
![18352459-C07A-480F-A11F-004ADBE461CF](https://user-images.githubusercontent.com/63832863/90001374-f24baa80-dcc3-11ea-992c-f02b1c9c6341.png)

**Comment by wongchito** [comment]
It can be accessed normally (just now). 

Please check your internet connection. Please also consider the possibility that your ISP has banned this hostname from connecting. 

If the problem still exists, you may try the [mirrored site hosted on GitLab](https://chitowong.gitlab.io/RailMapGenerator/).

**Comment by maliaoshui** [comment]
Still closed! (Not gitlab)
Wongchito.github.io/RailMapGenerator
