### ISSUE TITLE
我想增加上海地铁的模版

### ISSUE THREAD

**Issue by Thomastzc** [wongchito/RailMapGenerator#59]
这是压缩包，里面有1-18号线的线路json
[Shanghai Metro Board Json By Thomas.zip](https://github.com/wongchito/RailMapGenerator/files/5470054/Shanghai.Metro.Board.Json.By.Thomas.zip)

**Comment by Thomastzc** [comment]
不好意思，之前的有误，故重新上传
[Uploading Shanghai Metro Board Json By Thomas.zip…]()

**Comment by thekingofcity** [comment]
> 
> 
> 不好意思，之前的有误，故重新上传
> Uploading Shanghai Metro Board Json By Thomas.zip…

第二次的上传有点问题，麻烦等网页端显示上传成功后在提交回复。

非常感谢您的参与，在检查之后我们会将模板融入项目中。

**Comment by thekingofcity** [comment]
稍微预览了下，想确认下以下几点：

1. 部分站名存在恶搞行为，如人民扫广场等，是有意为之吗
2. 部分线路未标明换乘情况，如4，6，7，10号线等
3. 部分线路换乘线路时间不统一，如2号线无15号线换乘信息，但15号线有2号线
4. 部分线路换乘不对应，16号线龙阳路无磁悬浮，2号线有
5. 部分线路站台名未关闭，仍显示A站台，如15号线
6. 部分线路宽度不够，导致线路图站都挤在一起，如9号线
7. 部分线路线路名未修改，如7号线

**Comment by Thomastzc** [comment]
作者回复：
1。不算是，我们在制作中会玩梗，所以麻烦更改一下
2.大部分线路因不需要所以没有做换乘。
3.14，15，18三条新线路模板并非本人制作，而是朋友做的。
4.同上，且16是内置模板。
5.同“3”，本人拿到之后未经过更改
6.我在制作时没考虑线路图导致。
7.我只需要中间那块牌子，所以可能有疏忽。
综上所述，今晚我会再将所有模板检查一遍，然后上传
谢谢支持！
Ps：4号线，10号线的图不一样，希望像广州地铁一样能更改样式
Pss：能否制作环线呢。
Psss：就这些，谢。

**Comment by Thomastzc** [comment]
Pssss：能不能做到读取模板自动更改样式，比如我在mtr编辑时读取了shmetro的模板，能否自动更改。
Psssss：能否自动输出一串图片，比如说2号线从徐泾东到广兰路的站牌选好样式自动输出，不用一站一站输出了。

**Comment by thekingofcity** [comment]
> Ps：4号线，10号线的图不一样，希望像广州地铁一样能更改样式

具体是指4号线和10号线哪里的不同呢

> Pss：能否制作环线呢。

暂不支持环线，讨论请见#24

> Pssss：能不能做到读取模板自动更改样式，比如我在mtr编辑时读取了shmetro的模板，能否自动更改。

这个需要作者 @wongchito 的帮助，需要的话麻烦新开一个issue讨论

> Psssss：能否自动输出一串图片，比如说2号线从徐泾东到广兰路的站牌选好样式自动输出，不用一站一站输出了。

这个有在考虑，可能之后会添加此功能

---

另：暂未看到修改后的版本

**Comment by Thomastzc** [comment]
不好意思，修改好的版本还未上传

**Comment by Thomastzc** [comment]
这里有1-9，14，15，18的修改版
[Uploading 202011032105.zip…]()

**Comment by Thomastzc** [comment]
[Uploading 202011032105.zip…]()

**Comment by Thomastzc** [comment]
Line1-18,11080756终稿定稿版.ZIP

**Comment by Thomastzc** [comment]
[Line1-18,11080756终稿定稿版.ZIP](https://github.com/wongchito/RailMapGenerator/files/5505712/Line1-18.11080756.ZIP)
终于弄完了

**Comment by wongchito** [comment]
> Pssss：能不能做到读取模板自动更改样式，比如我在mtr编辑时读取了shmetro的模板，能否自动更改。

該功能暫未實現，但已在考慮當中

**Comment by Thomastzc** [comment]
> > Ps：4号线，10号线的图不一样，希望像广州地铁一样能更改样式
> 
> 具体是指4号线和10号线哪里的不同呢
> 贴图不同，L10有站点编号，L4有红色的一块
> > Pss：能否制作环线呢。
> 
> 暂不支持环线，讨论请见#24
> 
> > Pssss：能不能做到读取模板自动更改样式，比如我在mtr编辑时读取了shmetro的模板，能否自动更改。
> 
> 这个需要作者 @wongchito 的帮助，需要的话麻烦新开一个issue讨论
> 
> > Psssss：能否自动输出一串图片，比如说2号线从徐泾东到广兰路的站牌选好样式自动输出，不用一站一站输出了。
> 
> 这个有在考虑，可能之后会添加此功能
> 
> 另：暂未看到修改后的版本
已上传

**Comment by Thomastzc** [comment]
能不能回复呢

**Comment by thekingofcity** [comment]
您好，因为时间的关系只检查了6，7，8号线，然后我注意到了

* 6号线所有英文站名都简写了Road为Rd.，但我检查了下街景和百科好像都是全称，不知道有什么材料能支持简写吗
* 车站的换乘线路中文只有数字，英文只有Line，并不完整，导致了有些出站换乘的文字只有数字而无X号线

3，4号线因为共线和环线原因在可见的几个月内不会考虑，希望能您能理解

最后再次感谢您的积极参与

**Comment by Thomastzc** [comment]
[新建压缩(zipped)文件夹.zip](https://github.com/wongchito/RailMapGenerator/files/5589586/zipped.zip)
又改了一遍

**Comment by thekingofcity** [comment]
因为换乘线路的中英文仍然缺失部分信息，我可能要做一些脚本进行批量修复，这可能需要一点时间，感谢您的耐心等待和支持

**Comment by thekingofcity** [comment]
由于换乘线路的名称缺少**号线**和**Line**，需要通过以下正则表达式才能修复，所以进展缓慢，这次先更新下6号线和7号线，感谢您的耐心等待和支持

```
"(\d+)",\n(\s+)"Line(\d+)"
"$1号线",\n$2"Line $3"

"(\d+)",\n(\s+)"Line"
"$1号线",\n$2"Line $1"
```

**Comment by Thomastzc** [comment]
啥意思，我没看到更新啊------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;thekingofcity&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月27日(星期天) 晚上6:04
收件人:&nbsp;&quot;wongchito/RailMapGenerator&quot;<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;&quot;Thomastzc&quot;<3071765315@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 我想增加上海地铁的模版 (#59)

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/103774187-222a8e80-5067-11eb-9fd1-f6963b884f19.png)

源代码已更新，需要作者同步更新Github Pages才可以看到新的变化 : )

这次 b4b357e507ff2ba59f5b875022d46023cb177de4 主要是添加了8号线，虽然有增加更多线路的计划，不过在处理9，10号线时发现：

* 9号线的部分路名英文在单词内有大写
* 9号线蓝天路与14号线和杨高中路与18号线换乘信息暂未标注
* 10号线国权路与18号线换成信息暂未标注

最后感谢您的关注与支持，剩余的线路模板在您更新后会陆续合并到项目中

**Comment by Thomastzc** [comment]
您好，以下问题能否回答 1我到现在为止都未看见678的模板 2请问1.2.5的模板有添加么------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;thekingofcity&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月6日(星期三) 晚上9:41
收件人:&nbsp;&quot;wongchito/RailMapGenerator&quot;<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;&quot;Thomastzc&quot;<3071765315@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 我想增加上海地铁的模版 (#59)

**Comment by thekingofcity** [comment]
1. > 源代码已更新，需要作者同步更新Github Pages才可以看到新的变化 : )

    如我之前回复所说的，需要作者的更新才可以看到。现在作者已经更新了，您应该能在官网上刷新后看到变化，如同我截图里的那样 : )

2. 1,2,5号线都是之前已经上传的模板，线路没有变化的话应该不会进行修改了

**Comment by Thomastzc** [comment]
有一个问题，我今天早上加载时最后一张图就是出不来，而且刷新过好多次了 还问作者是否愿意加qq说呢，GitHub登录太烦了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;thekingofcity&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月7日(星期四) 中午12:44
收件人:&nbsp;&quot;wongchito/RailMapGenerator&quot;<RailMapGenerator@noreply.github.com&gt;;
抄送:&nbsp;&quot;Thomastzc&quot;<3071765315@qq.com&gt;;&quot;State change&quot;<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] 我想增加上海地铁的模版 (#59)

**Comment by thekingofcity** [comment]
代原作者上传9号线更新版本

[Line-9.json.txt](https://github.com/wongchito/RailMapGenerator/files/5871885/Line-9.json.txt)

**Comment by thekingofcity** [comment]
> 
> 
> 代原作者上传9号线更新版本
> 
> [Line-9.json.txt](https://github.com/wongchito/RailMapGenerator/files/5871885/Line-9.json.txt)

检查了下9号线的版本，除了若干英文名比如Tai'erzhuang应为Taierzhuang，SongJiang University应为SongJiang University Town以外，还缺少了松江新城站。由于详细校对的时间仅略少于重新制作，所以添加的模板名中不会包括`by Thomastzc`的信息，您看这样可以吗？

**Comment by thekingofcity** [comment]
检查了下10号线的存档，发现的错误有陕西南路站英文应为South Shaanxi Road而不是South Shanxi Road、交通大学英文应为Jiao Tong University而不是Jiaotong University、以及所有换乘线路不提供英文名等。

同时还增加了14和18号线的换乘信息，以及更新了新天地的新名称，一大会址·新天地。

由于详细校对的时间仅略少于重新制作，所以添加的模板名中不会包括`by Thomastzc`的信息，您看这样可以吗？

**Comment by thekingofcity** [comment]
14和18号线由于暂未开通暂不处理，静等年底 😀

**Comment by Thomastzc** [comment]
十八号线其实可以上啦，目前各站吊板均为长南到航头版本

**Comment by thekingofcity** [comment]
Hi, we would like to thank you for your contribution, so we put your name in the `info` panel and project `readme`. Looking for more!

![image](https://user-images.githubusercontent.com/3353040/139860647-01283189-938b-4a02-8ef6-813de8d25165.png)

**Comment by thekingofcity** [comment]
嗨，最后两条线路14号线和18号线在压缩包中均为15号线，那此issue变无open的必要。

**Comment by Thomastzc** [comment]
我找到了之前制作的14，18号线吊板
[18号线.zip](https://github.com/wongchito/RailMapGenerator/files/7797737/18.zip)
