### ISSUE TITLE
增加一些上海地铁的线路

### ISSUE THREAD

**Issue by Tianxiu11111** [wongchito/RailMapGenerator#60]
[Shanghai Metro Line 11.zip](https://github.com/wongchito/RailMapGenerator/files/5501582/Shanghai.Metro.Line.11.zip)

**Comment by Tianxiu11111** [comment]
[Uploading Shanghai Metro Line 2.zip…]()

**Comment by Tianxiu11111** [comment]
[Shanghai Metro Line 2.zip](https://github.com/wongchito/RailMapGenerator/files/5501741/Shanghai.Metro.Line.2.zip)

**Comment by thekingofcity** [comment]
非常感谢您的热情参与，在我进行微调后会上线这两条线路

**Comment by Tianxiu11111** [comment]
[Shanghai Metro Line 5.zip](https://github.com/wongchito/RailMapGenerator/files/5504601/Shanghai.Metro.Line.5.zip)

**Comment by Tianxiu11111** [comment]
作者您好，我又制作了新线路

**Comment by thekingofcity** [comment]
已将新的三条线路加入项目中，静候 @wongchito 大大更新gh-pages

PS: 2号线龙阳路站增加了磁悬浮图标，其余几条线路微调了站板宽高度

**Comment by wongchito** [comment]
b9e759fd24c53865770fb72a0b69f3b95b404037 f81ddfd

GitHub Pages / GitLab Pages 已更新並加入相關路線範本。感謝閣下的支持！

註：閣下的GitHub用戶名稱將載於範本選框對話框的列表內，如閣下不欲公開用戶名稱，或欲以其他方式被載入開發人員列表（如加入commit作者列表），請及時與我們聯絡！

**Comment by thekingofcity** [comment]
Hi, we would like to thank you for your contribution, so we put your name in the `info` panel and project `readme`. Looking for more!

![image](https://user-images.githubusercontent.com/3353040/139860647-01283189-938b-4a02-8ef6-813de8d25165.png)
