### ISSUE TITLE
Issues about gzmtr style 关于广州地铁格式的问题

### ISSUE THREAD

**Issue by gazeta-issuesormakers** [wongchito/RailMapGenerator#66]
There's some issue in this style. Such as "Xilang Station" in Guangzhou Line 1. **Plaftorms may have arrows in terminal ways.**
在这个格式中有一点问题。比如广州1号线的“西塱站”。**终点站的标牌也是有箭头的。**

**Comment by wongchito** [comment]
Hi! Could you please provide photos of Xilang station for reference. Thanks.

**Comment by gazeta-issuesormakers** [comment]
(I'm not say there's all wrong in issue 我没说这里全都是错误 ) 
In now, There's only not-underground stations in Guangzhou had a different style on way.
按现在来讲，广州只有非地下站台是不同的格式。
Here's a reference. 这是一个实例。
![e66b00b358e6764bfd7041abb9225721](https://user-images.githubusercontent.com/76482244/105050759-14362e00-5aa9-11eb-9e22-886ae07833e7.jpeg)
Xilang Station's plaftorms has no plaftorm that says this station is the termial(means there're all the opposite direction).
西塱站没有任何一个站台是说这个是终点站（指的是所有站台都是返程方向）
Another example is "Xinhe"**,the termial station of Guangzhou Line 14**.
还有一种例子是“新和”站，**广州14号线的终点站**。
![14ce36d3d539b6008e2fa36ce750352ac75cb70c](https://user-images.githubusercontent.com/76482244/105051251-8c9cef00-5aa9-11eb-92ba-25bc17322a02.jpg)

It means this style isn't complete.
这个代表着此格式不完全。

**Comment by wongchito** [comment]
Thanks for the information. 

At the moment, you may change the direction such that it's pointing towards the other end of the lines, as RMG gives you the flexibility to customise your map.
