### ISSUE TITLE
上海轨道交通18号线已经制作完成

### ISSUE THREAD

**Issue by Tianxiu11111** [wongchito/RailMapGenerator#67]
[Shanghai Metro Line 18.zip](https://github.com/wongchito/RailMapGenerator/files/5787881/Shanghai.Metro.Line.18.zip)

**Comment by Tianxiu11111** [comment]
另：作者您好，在上海地铁站名牌中，两个字的站名中间通常会加一个空格，如图

<img width="417" alt="1" src="https://user-images.githubusercontent.com/74058475/104031062-3c9b6e00-5207-11eb-8d05-642fc26d9558.PNG">

**Comment by thekingofcity** [comment]
嗨，我打算在18号线年底一期都开通后再添加，主要是考虑到站名还有可能会有改动？

**Comment by thekingofcity** [comment]
Hi, with the arrival of 2022, we wish you a happy new year 🎉

We would like to thank you for your patience and contribution to this amazing line 18 template. It is added in 5f4f082 and released in 3.10.28.
