### ISSUE TITLE
广州地铁8号线画布问题 Guangzhou Line 8 canvas issue.

### ISSUE THREAD

**Issue by maliaoshui** [wongchito/RailMapGenerator#69]
Guangzhou Metro L8 Cultural Park to Jiaoxin is opened.
广州地铁8号线文-滘段已经开通。

**Comment by maliaoshui** [comment]
Cultural Park to Jiaoxin opened.
文化公园到滘心已开通。

**Comment by wongchito** [comment]
The template for Guangzhou Metro Line 8 has been updated in version 3.8.33
<img width="266" alt="image" src="https://user-images.githubusercontent.com/9390786/118365626-24ca6100-b5d0-11eb-8810-8d2d1d76752f.png">
