### ISSUE TITLE
增加上海地铁12号线

### ISSUE THREAD

**Issue by Andy1782010** [wongchito/RailMapGenerator#70]
这是文件
[rmg.param.12号线.zip](https://github.com/wongchito/RailMapGenerator/files/5923380/rmg.param.12.zip)

**Comment by Andy1782010** [comment]
如有问题，敬请谅解

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/135788881-de6e9519-5d92-4698-bc35-5cfdf8aa04cb.png)

除了申江路的英文有一点点问题以外其他都ok，模板的名字会展示`by Andy1782010`😊
