### ISSUE TITLE
Can not  open the web page

### ISSUE THREAD

**Issue by BlueSky218-mike** [wongchito/RailMapGenerator#75]

**Comment by thekingofcity** [comment]
The project looks fine on my machine :(

Could you provide more information such as:
* network type (Wifi, Lan, Cellular, etc)
* network ISP (Telcom, Mobile, Unicon, etc)
* use proxy or not
* Web browser type and version (Chrome, Firefox, Edge, etc)
* OS type and version

By the way, besides the *github* version, those with poor github connection may switch to use *gitlab* version at https://chitowong.gitlab.io/RailMapGenerator
