### ISSUE TITLE
何时可以增加北京地铁线路图模板

### ISSUE THREAD

**Issue by pishen635** [wongchito/RailMapGenerator#78]

**Comment by Clebohto** [comment]
正在做 但是懒)

**Comment by thekingofcity** [comment]
如果说的是线路图的话，#118 已经加入了*1，2，4~6，八通和首都机场线*。如果您也感兴趣的话欢迎提交使用RMG制作的存档，交由我们来发布到项目中。

如果说的是风格(即指的北京地铁样式的画布)的话，目前来说两位作者还没有计划(逃
