### ISSUE TITLE
请尽早把这个标注删除 Please delete this mark as soon as possible

### ISSUE THREAD

**Issue by NiuBoss123** [wongchito/RailMapGenerator#79]
不多说，先上图片：
Please delete this mark as soon as possible:
![Screenshot_20210503_005838_com huawei browser](https://user-images.githubusercontent.com/62463715/116821089-06fe0480-abab-11eb-9ca5-f75efdd3b781.jpg)
看见了吗？看见了吗？
Did you see it?  Did you see it?

如果查阅广州地铁的线路图，可以发现类似于这样的（图片取自地铁通）
 If you check the route map of Guangzhou Metro, you can find something similar to this (picture taken from MetroMan)
![Screenshot_20210503_010248_com xinlukou metroman](https://user-images.githubusercontent.com/62463715/116821194-770c8a80-abab-11eb-8d78-715c3d446b10.jpg)

没错，他已经开通了，然而那个不该出现的标识却还在
希望尽早去除，避免误导
Yes, he has activated it, but the sign that shouldn’t appear is still there
 Hope to be removed as soon as possible to avoid misleading

（英文翻译使用谷歌翻译，如有错误请指正）

**Comment by NiuBoss123** [comment]
希望能尽早处理，因为通车不是一个月那么简单了

**Comment by wongchito** [comment]
Duplicate #69
