### ISSUE TITLE
New runin terminal style of Shanghai Metro 2020

### ISSUE THREAD

**Issue by Thomastzc** [wongchito/RailMapGenerator#83]
今天看到了这种
[https://user-images.githubusercontent.com/73764348/123019395-f7f53f00-d402-11eb-90cc-d67073e4e6ba.png](url)
或者是
![rmg 2021-06-23T01_04_20 491Z](https://user-images.githubusercontent.com/73764348/123021198-38a28780-d406-11eb-96f5-42ce75b2d1ff.png)

**Comment by thekingofcity** [comment]
麻烦提供一下json格式的存档，想复现一下

**Comment by Thomastzc** [comment]
我使用了Windows画图，我是说在地铁站看到这这种类型的牌子，不好意思

**Comment by Thomastzc** [comment]
做法就是在终点站后面再加一站，然后导出，再给他P掉。我的意思是说我们能否制作出这样的牌子，现在各终点站牌都在更换

**Comment by thekingofcity** [comment]
有实景图片提供吗，最近没怎么到终点站过

**Comment by Thomastzc** [comment]
10号线红火，基隆路 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月23日(星期三) 下午5:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] look at this (#83)

**Comment by thekingofcity** [comment]
图片好像没有正确显示，可以直接将图片拖到回复框中

**Comment by Thomastzc** [comment]
emm.like this
[https://img.zhouii.com/imghost/metro/IMG_20210110_145430.jpg/watermark_l](url)
orlike this
[https://img.zhouii.com/imghost/metro/IMG_20210110_145735.jpg/watermark_l](url)

**Comment by Thomastzc** [comment]
同时，终点站牌也做了更新，类似于上海地铁4号线的双方向样式
[https://img.zhouii.com/imghost/metro/IMG_20210110_201412.jpg/watermark_l](url)

**Comment by thekingofcity** [comment]
> emm.like this
> [https://img.zhouii.com/imghost/metro/IMG_20210110_145430.jpg/watermark_l](url)
> orlike this
> [https://img.zhouii.com/imghost/metro/IMG_20210110_145735.jpg/watermark_l](url)

很有意思的更改，会在之后的更新中加入sh2020样式

**Comment by thekingofcity** [comment]
> 同时，终点站牌也做了更新，类似于上海地铁4号线的双方向样式
> [https://img.zhouii.com/imghost/metro/IMG_20210110_201412.jpg/watermark_l](url)

这里我没有看出和之前有什么区别

**Comment by Thomastzc** [comment]
双终点站牌，竖着放的 ------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月24日(星期四) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] look at this (#83)

**Comment by Thomastzc** [comment]
谢谢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月24日(星期四) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] look at this (#83)

**Comment by thekingofcity** [comment]
> 双终点站牌，竖着放的

理解了，会一起修掉的

**Comment by thekingofcity** [comment]
在以上两个commit中修复

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/124385091-e109f300-dd06-11eb-94ea-8660c008902c.png)

![image](https://user-images.githubusercontent.com/3353040/124385103-f67f1d00-dd06-11eb-9aff-879b68a2f42c.png)

**Comment by Thomastzc** [comment]
emm。今天我在四号线时发现竖着放的双终点站牌子有两种格式，1是分别的往……，To……
一种是在箭头后面直接放上往

**Comment by Thomastzc** [comment]
emm。今天我在四号线时发现竖着放的双终点站牌子有两种格式，1是分别的往……，To……
一种是在箭头后面直接放上往
                                                To
后面再接上两个终点站名称

**Comment by thekingofcity** [comment]
> 
> 
> emm。今天我在四号线时发现竖着放的双终点站牌子有两种格式，1是分别的往……，To……
> 一种是在箭头后面直接放上往
> To
> 后面再接上两个终点站名称

有实景图吗

**Comment by thekingofcity** [comment]
顺带一提两行终点站的格式是不是应该属于2020新风格？
