### ISSUE TITLE
Station mismatch at the bifurcation point

### ISSUE THREAD

**Issue by Thomastzc** [wongchito/RailMapGenerator#84]
![rmg 2021-06-27T00_21_10 038Z](https://user-images.githubusercontent.com/73764348/123529227-df499980-d720-11eb-98f7-71ddb59aa86d.png)
![rmg 2021-06-27T00_23_16 410Z](https://user-images.githubusercontent.com/73764348/123529234-f1c3d300-d720-11eb-8871-97935b0dbbc3.png)
this seems to be wrong

**Comment by Thomastzc** [comment]
向上分叉的点应该在东川路和江川路之间，往上叉

**Comment by Thomastzc** [comment]
Another problem
![rmg 2021-06-27T00_27_11 258Z](https://user-images.githubusercontent.com/73764348/123529382-30a65880-d722-11eb-9bc1-3e61c5db536b.png)
浦东国际机场没有转乘磁浮线的标识
![屏幕截图 2021-06-27 083030](https://user-images.githubusercontent.com/73764348/123529391-49af0980-d722-11eb-9cec-b3836136554d.png)
这个 名字太长了，反斜杠的没法子换行

**Comment by thekingofcity** [comment]
> 向上分叉的点应该在东川路和江川路之间，往上叉

这时一个已知问题，这里的实现与新功能indoor的主线支线分叉有关

在新的解决方案出现之前我会revert到老版本(指偏移30px的实现方式

**Comment by Thomastzc** [comment]
indoor啥时候出来呢------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月29日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wongchito/RailMapGenerator] hmm^ (#84)

**Comment by thekingofcity** [comment]
进一步的调查显示是5号线的模板制作有问题，导致存档中的数据不合法

**Comment by thekingofcity** [comment]
尽管存档的数据有问题，但是画图的实现也有问题

**Comment by thekingofcity** [comment]
![image](https://user-images.githubusercontent.com/3353040/125468833-d877625d-eb5c-4712-b7d3-7d1425233b51.png)

**Comment by thekingofcity** [comment]
fixed and released in 3.9.2
