### ISSUE TITLE
More destinations in branch of Shanghai style

### ISSUE THREAD

**Issue by Thomastzc** [wongchito/RailMapGenerator#90]
终点站双终点，分别是莘庄和闵开发

**Comment by thekingofcity** [comment]
这是一个有意思的现象，首先要确认有支线的5，10，11都是同样的表现形式，如果有实景图参考就好了

**Comment by Thomastzc** [comment]
https://img.zhouii.com/imghost/metro/IMG_20200828_143025.jpg/watermark_l
我看到11号线也是这么写的，但是10号线只写了往新江湾城。
还有两个特殊的地方，我觉得可以新开一个样式“上海地铁11号线特殊版本”
1.站名牌文字使用旧版的左右结构，但是方向条是从中间到右边的。
2.https://img.zhouii.com/imghost/metro/IMG_20200828_145224.jpg/watermark_l
类似于这个，分叉是直着往上走的

**Comment by thekingofcity** [comment]
> https://img.zhouii.com/imghost/metro/IMG_20200828_143025.jpg/watermark_l
> 我看到11号线也是这么写的，但是10号线只写了往新江湾城。

我对于不统一的格式没有非常强的实现冲动，大概率保持原样不变了

> 还有两个特殊的地方，我觉得可以新开一个样式“上海地铁11号线特殊版本”
> 1.站名牌文字使用旧版的左右结构，但是方向条是从中间到右边的。
> 2.https://img.zhouii.com/imghost/metro/IMG_20200828_145224.jpg/watermark_l
> 类似于这个，分叉是直着往上走的

第一点同理
对于第二点，我想确认是不是2020年新的样式，比如5，10号线是否也是同样的直角呢？

**Comment by thekingofcity** [comment]
由于长时间未收到新的回复而关闭😀
